### ISSUE TITLE
Request for clarification about timeouts (1006) when sending long messages.

### ISSUE THREAD

**Issue by NathanRichard** [aaugustin/websockets#1005]
Hello,

This is not a bug report, but rather a request to clarify websockets behavior regarding connection timeouts when sending big messages.

# Context

In my application I use websockets so that several clients (which can be behind slow DSL complexions with NAT) can communicate with my server (which has a public IP). Due to the slow DSL connections, sending big messages from the clients to the server can take a long time (> 60 seconds), I have been able to correlate this with connections failing due to 1006 errors.

# Diagnostic

I have read several related issues :
https://github.com/aaugustin/websockets/issues/587
https://github.com/aaugustin/websockets/issues/977

My understanding of the issue is only one data-transfer can be in progress at any time in the websocket connection, and that a ping timeout counts as a data-transfert. So as long as the application message sending is only, pings cannot be processed.

So far I managed to keep this under control by limiting the message size and increasing the ping settings (ping_interval, ping_timeout), so that sending a message never takes longer than ping_timeout even in the worst case scenario. I also prefer not to disable the pings entirely as I want to be able to detect clients crashes and shutdowns in the server. 

# Questions
However this solution is not optimal as a few users with slow connections forces me to reduce the message size (which has other impacts in my application) for all users. I would like to find a better solutions so here are my questions :

- Is my understanding of the issue correct (big messages preventing the ping processing) ?
- Would disabling ping entirely prevents my server from detecting client crashes or abrupt shutdowns (ie not enough time to close properly the client) ?
- Could disabling ping could have a negative impact on proxys closing the idle connections (Kong for instance) ?
- Would it be possible to solve this issue by making ping *smarter* ? I understand I the one-message-at-a-time constraint is an important design decision that probably as other benefits for the library, but basically pings are not useful when a data-transfer is ongoing ; the transfer itself is doing ping's job by making sure that there is somebody at the other end of the line. So could we have the ping process detect that there is already something going on on the connection and put himself on hold (and don't timeout the connection) ?

Finally I wanted to thank you for sharing the work you put in websockets. I has been an efficient and valuable piece of software for my projects.

Best regards,
Nathan

**Comment by lgrahl** [comment]
> Is my understanding of the issue correct (big messages preventing the ping processing) ?

Yes. What you're describing is [head-of-line blocking](https://en.wikipedia.org/wiki/Head-of-line_blocking), a characteristic of TCP.

> Would disabling ping entirely prevents my server from detecting client crashes or abrupt shutdowns [...]?

Somewhat. You're falling back to TCP connection loss detection which will usually take longer. For periods where no data is transmitted, TCP connection loss detection may not work at all up until the point you're starting to transmit data. Then, all of a sudden, connection loss is detected.

> Would it be possible to solve this issue by making ping smarter?

Absolutely but I'm not sure that is something the library should do because it is highly use case dependent. For example, if you do not care about responsiveness and just want to detect connection loss in a specific time X:

- Send a ping when no data has been sent or received within X/2, create a timer that waits at most X/2 and marks the connection as lost if no pong or data is received within that time period
- When a ping is received, send a pong
- When any data or a pong is being received, clear the ping timeout timer

This might be achievable with specific TCP socket settings as well - I am not sure.

**Comment by NathanRichard** [comment]
Hello @lgrahl thanks for your quick reply.

Given your comment about this change belonging or not in the library, I am not sure if the algorithm you proposed is something I should implement in my application (in such cases are library internals like the ping timeout timer available to the app ?) or a way to implement it in the library.

I understand that sending multi-Mio payloads might not be something that most users do with this lib, but I still think that there are several good reasons to implement it on the library :
- Pings are built-in the library and enabled by default so it is only consistent that they work well with other basic library features like sending messages.
- Sending big messages is actually supported by the library ; the [docs actually state what configuration changes must be made to support multi-Mio payloads](https://websockets.readthedocs.io/en/stable/deployment.html#buffers), but it says nothing about the interactions with the pings.
- I find it counter intuitive that ping timeouts should be tuned according to message size, contrary to other parameters like requests timeouts for instance.
- Client connection speed is unpredictable. What I am experiencing with big messages and DSL connections, others might be with smaller messages and slower 2G or Edge connections.

Please understand I am not trying to have somebody else solve this for me ; I am happy to help with a fix but would need some guidance as I am not familiar with the websockets codebase.

**Comment by lgrahl** [comment]
The "layering" of keep-alive is just my personal opinion. I think the default keep-alive mechanism of websockets already goes too far but Aymeric and you may disagree which is perfectly fine. :slightly_smiling_face: Note that *pings* and *pongs* are defined by the WebSocket protocol while there is nothing in the spec dictating when to use them.

Nits aside, I'd estimate that @aaugustin would not disapprove a solution that refreshes the ping timeout timer on any data received which is pretty much exactly what you're looking for. That feature could then be exposed via a simple flag in the API.

**Comment by lgrahl** [comment]
Regarding pointers, this is where the wait for a pong happens after a ping and where the timeout could be reset when any data has been received: https://github.com/aaugustin/websockets/blob/b2a95c45fae19fff0a3473158dd02afe2ca42604/src/websockets/legacy/protocol.py#L1118

**Comment by aaugustin** [comment]
In fact you can work around head-of-line blocking with fragmentation.

If you convert a 1MB message in a list of a hundred 10kb chunks, then pings can be sent between chunks _when the send buffer fills up_. This begs a question of the size of the TCP send buffer, which can be too large — I don't remember the defaults on common operating systems.

**Comment by NathanRichard** [comment]
Hello @aaugustin,

Can you develop your point about fragmentation ? 

Do you mean splitting the message into smaller ones ? In my case this may not be practical because I use a json-rpc protocol on top of websockets with both the client and the server defining several services. So calling a service several times with smaller messages is not the same as calling once regarding the application semantics.

Or is there a way to send such a list in a single call to websockets ? Actually I though that the send() call could only accept a str or bytes instance, but the doc does mention fragmented message. API-wise, how does that translate ; can send() accept iterators or generators ?

Regarding the effect of such a fragmented message, the doc states that [_"Only one coroutine can receive messages at a time"_](https://websockets.readthedocs.io/en/stable/design.html) and [_"Sending a fragmented message forces serialization"_](https://websockets.readthedocs.io/en/stable/design.html) : does that mean that pongs are a special case ?

Thanks for your help.

**Comment by aaugustin** [comment]
> Can you develop your point about fragmentation ?

Do `await asyncio.send(["abc", "def", "ghi"])` instead of `await asyncio.send("abcdefghi")`.

**Comment by aaugustin** [comment]
Quoting the docs:

> send() also accepts an iterable or an asynchronous iterable of strings, bytestrings, or bytes-like objects. In that case the message is fragmented. Each item is treated as a message fragment and sent in its own frame. All items must be of the same type, or else send() will raise a TypeError and the connection will be closed.

**Comment by lgrahl** [comment]
If the send buffer (TCP + websockets) is full because the network is slow, it doesn't help trickling in ping messages because they'd still be at the end of the buffer, hence having a chance to time out even if the data flows perfectly fine. If both sides have full send buffers, the problem gets worse.

I think there are two use cases for ping:

- checking that the connection is still working, and
- checking that the connection is responsive (measuring RTT).

Arguably, most use cases will fall into the first category. Resetting the ping timeout timer would not hurt these at all and avoid the need of unnecessary message fragmentation. To me, that is a good rationale to implement such a change.

**Comment by aaugustin** [comment]
Since the constraints here ("I want to send multiple MB messages") are pretty far outside the most common use cases of websockets ("I want to send 1kb messages") the default settings need adjusting. Documenting this is one option.

The keepalive behavior is a common source of questions but I think it works well in most cases and it's very easy to understand by looking at the logs. I'm a bit wary of changing it in such a way that "read the logs" no longer suffices for debugging.

**Comment by lgrahl** [comment]
Understandable. @NathanRichard you can still implement a custom keep-alive mechanism based on the `ping` method since that is accessible to you. It would basically be a copy of the existing keep-alive mechanism of websockets (which is very simple) plus the pong timeout timer reset (which should also be simple) that I mentioned.

**Comment by NathanRichard** [comment]
Hello,

Thanks @lgrahl for the pointers.

@aaugustin I understand your reluctance to change the default behavior of the keepalive system. However if I implement the changes that @lgrahl suggested, is there a chance that you would accept a merge if they are protected by a switch disabled by default (so the behavior changes only for people who activate the option) ?

My thinking is that way it could benefit others, even if only a few share my use case.

Best regards,
Nathan

**Comment by aaugustin** [comment]
Well, it isn't clear to me that there's a clear frontier between "the connection is still working" and "the connection is responsive".

As packet loss increases — this is the realistic scenario that requires keep-alive; hard disconnections are detected immediately — a TCP connection gradually transitions from "responsive" to "not super responsive" to "clogged" to "non functional in practice even if the TCP stack still believes that it could recover" to "definitely dead" (after 2 hours with common TCP settings). If you wait long enough, perhaps the connection will eventually recover.

If you implement a different mechanism, it isn't clear to me that it will provide substantially different and more desirable characteristics that the current mechanism (with suitable parameters).

----

In order to determine if it's worth the effort, you could try documenting:

- how your proposed mechanism works?
- under which circumstances it should be preferred to the default mechanism and why?

If the result is clear, the decision is easy to make for all users, the new option adds value for a wide range of use cases, and you're willing to write an implementation matching websockets' standards (100% branch coverage) then I may accept the burden of maintaining this implementation in the future.

At this point I'm not convinced it adds enough value to outweight the cost of inflicting a choice on users, even a simple one. Furthermore, I expect that, when you attempt to document the feature, you will realize that it's a fairly complicated choice.

**Comment by NathanRichard** [comment]
@aaugustin Thanks for your reply.

I don't think my change will meet the *"adds value for a wide range of use cases"* requirement, so I will implement on my application layer.

Thanks again for your detailed explanations and pointers regarding the implementation.
