### ISSUE TITLE
Doc fails to show Producer code

### ISSUE THREAD

**Issue by gitcnd** [aaugustin/websockets#1022]
The doc has this:

`    message = await producer()
`
But it does not tell us how to define that - do we need async? what format should the return value be in?

Please add a working _producer_ example, so we don't have to guess.

**Comment by aaugustin** [comment]
Thanks for reporting this.

Here are the reasons why I haven't provided an example of `producer()` — I'm not saying they're good reasons, merely obstacles I faced:

- since this is the intro, I want to focus on the core mechanics of a long-lived, bi-directionnal connection;
- I didn't come up with a good idea that would make sense, fit in one or two lines, and not distract the reader with more questions.

Besides, I'm trying to maintain a frontier between "writing a tutorial for websockets" and "writing a tutorial for Python and asyncio". Currently the docs define producer as "a `producer` coroutine". Knowing that you define a coroutine with `async def producer(): ...` falls on the "asyncio tutorial" side of the line. I don't want to go into explaining that.

You have a valid point about which types `send` can accept. I assume people would naturally try a `str`, find that it works, and maybe discovered later that `bytes` work too.

I have a longer-form tutorial in a local branch, with a more gradual and detailed explanation of these concepts, but it's very far from done :-/

**Comment by pvcraven** [comment]
I'd like to second a request for a more complete set of example code here on the page I assume we are talking about:
https://websockets.readthedocs.io/en/stable/intro/index.html

I also am not sure how to work the "handler" function in that set of docs. It takes a websocket and a path as parameters. So what does the code around handler look like? There's no explanation as to what the "path" parameter is, despite is showing up in example code.

An example that takes messages off a Queue and sends them, while putting received messages on a Queue for processing by a different thread might be generic enough.

**Comment by aaugustin** [comment]
The `path` parameter will be removed in the next version of websockets.

Your question sounds a bit like "I see the kit but I don't see how the pieces fit together so I'm unable to use it". If so, maybe a better tutorial would help?

**Comment by pvcraven** [comment]
Correct, I am unable to see how the pieces fit together, and having no luck at progressing. I don't know, maybe a tutorial on a chat program? That might be short enough, yet show producer/consumer on both client and server.

I've found that with "websockets" as generic term, finding help on StackOverflow is hard. There's no discord so I can't ask casual questions. I'm pretty sure this is exactly the library/functionality I'm looking for, I just can't quite find the way there.

**Comment by aaugustin** [comment]
The new tutorial is #1062 - still WIP. You'll run into trouble if you attempt to follow it with websockets 10.0 because it depends on some changes that will be in 10.1. It is not a chat program because I wanted to avoid the cliché of WebSocket tutorials ;-)

**Comment by aaugustin** [comment]
Coming back to this:

> An example that takes messages off a Queue and sends them, while putting received messages on a Queue for processing by a different thread might be generic enough.

If you declare:

```python

queue = asyncio.Queue()

consumer = queue.put

producer = queue.get
```

Then the current example does what you describe (I think).

**Comment by aaugustin** [comment]
... which suggests that I could just rewrite the example to use `queue.put` instead of an abstract `consumer` and perhaps it would be clearer?

**Comment by pvcraven** [comment]
An example with a queue would be perfect for me, and I feel it would be generic enough anyone could use it.

I don't see where in the PR that it is showing exactly how to integrate the handler into a client or server, but I could easily be missing that.

Looks like you are starting a Connect4 example, which also has the functionality I'm probably looking for, except I'll have a Python client instead of JS. (I'm trying to write a tutorial for the Python Arcade library on using Websockets to make a multiplayer game.)
