### ISSUE TITLE
run pytest error no 99

### ISSUE THREAD

**Issue by summy00** [aaugustin/websockets#1130]
when I run `pytest -s legacy/test_client_server.py`
```
OSError: [Errno 99] error while attempting to bind on address ('::1', 0, 0, 0): cannot assign requested address

/usr/local/lib/python3.9/asyncio/base_events.py:1494: OSError
```
python 3.9.6
any suggestion? thx!

**Comment by aaugustin** [comment]
I'm not sure what's happening or that I can do anything about it in websockets. This is failing either because you cannot bind to ``::1``, which would be a system configuration issue on your machine, or because you cannot bind any port (``0`` means "any port you like"), which would mean you ran out of ports. I cannot diagnose that without access to your machine. If you figure it out and you can suggest an addition to the docs, please comment and I'll reopen this issue. Thank you!

**Comment by aaugustin** [comment]
This could also be a duplicate of #1102.
