### ISSUE TITLE
Websockets documentation examples ignore path

### ISSUE THREAD

**Issue by raldi** [aaugustin/websockets#1154]
All the examples of how a websockets server is supposed to behave show the callback taking the requested path as a parameter... and then completely ignoring it. For instance:

https://websockets.readthedocs.io/en/stable/intro/tutorial2.html

Can you update the documentation to show what a server is supposed to do when it receives a request that has an invalid path?

**Comment by aaugustin** [comment]
If you don't recognize the path, just close the connection:

The intended pattern for this in the latest version of websockets would be:

```python
async def handler(websocket):
    if websocket.path != "/":
        return
```

**Comment by aaugustin** [comment]
I removed the `path` parameter precisely because many websocket servers:

- either serve a single endpoint, so they don't care (similar to how you can tack arbitrary query params on HTTP requests and most HTTP servers will be fine with that)
- or decide which endpoint to serve based on the first message sent on the connection rather than the path

To me, `path` is more of a side effect of the decision to design the WebSocket handshake for compatibility with HTTP/1.1 
than something useful.
