### ISSUE TITLE
Multithreaded client

### ISSUE THREAD

**Issue by fmfranck** [aaugustin/websockets#1206]
Is it possible to multithread a python websockets client :
- thread 1 or asyncio : Wait on message reception, handle them as soon as available
- thread 2 or asyncio : Send messages immediatly when available on a queue 

Without consuming much CPU or polling ?
Thanks

**Comment by aaugustin** [comment]
Yes, but with coroutines, not with threads.

https://websockets.readthedocs.io/en/stable/howto/faq.html#how-do-i-run-two-coroutines-in-parallel

**Comment by fmfranck** [comment]
Thanks

Le lun. 15 août 2022 à 11:34, Aymeric Augustin ***@***.***> a
écrit :

**Comment by Vincent-Stragier** [comment]
Hi @aaugustin,

The link you gave is not working any more, here is the new one: https://websockets.readthedocs.io/en/stable/faq/asyncio.html#how-do-i-run-two-coroutines-in-parallel

Also, I had to scratch my head since I'm not familiar with Asyncio and I needed to start a process (which implied the use of Queue). Little did I know that Queue are not suited for Asyncio (at first sign, it seems to work, then you realize [you are not receiving any message](https://websockets.readthedocs.io/en/stable/faq/asyncio.html#why-does-my-program-never-receive-any-messages), but for [a different reason](https://stackoverflow.com/questions/56645676/multiprocess-queue-synchronization-with-asyncio#)).

For the moment, I'm using the following snippet: https://gist.github.com/Vincent-Stragier/11a5258ea26544f5c91f5a625f57499a

@aaugustin, thanks for your work :-)

Best,
Vincent

**Comment by aaugustin** [comment]
This will be easier once #1245 is done. I made some progress last week-end but it isn't finished yet.
