### ISSUE TITLE
Multiple headers with same name leads to an exception

### ISSUE THREAD

**Issue by iudeen** [aaugustin/websockets#1208]
When adding multiple headers with same names, example: 

```
"headers": [(b"server", b"over-ridden"), (b"server", b"another-header")]
```
we get `MultipleValuesError`

Is there any particular reason for this validation? 

This happens when using the client as well, if the server sets multiple headers with same name.

**Comment by aaugustin** [comment]
This is happening because `headers["key with multiple values"]` is ambiguous. Use `headers.get_all("key with multiple values")` to get a list of all values in places where you need to deal with that case.

For most HTTP headers, multiple values just don't happen, so assuming there's a single value and raising an exception if there's more than one is the most convenient.
