### ISSUE TITLE
SIGTERM handling

### ISSUE THREAD

**Issue by wolframm** [aaugustin/websockets#124]
Hi,
It would be extremely helpful if you could provide an example on how to gracefully shut down the consumer pattern when receiving a SIGTERM from the command line (Ctrl+C).
I am already on my third day trying to figure this one out, without much success so far.
Kind regards,
Arne

**Comment by wolframm** [comment]
Just figured it out. Thanks for your really module, anyways. : )

**Comment by aaugustin** [comment]
Would you mind sharing your solution? I could help someone else! Also, if I Iike it, I may include it in the docs. Thanks!

**Comment by wolframm** [comment]
Here it is. It's very basic. Up to you if you want to use it.

killer.py

```python
import signal

__kill_now = False

def __set_kill_now(signum, frame):
    print('\nRECEIVED SIGNAL', signum)
    global __kill_now
    __kill_now = True

signal.signal(signal.SIGINT, __set_kill_now)
signal.signal(signal.SIGTERM, __set_kill_now)

def kill_now() -> bool:
    global __kill_now
    return __kill_now
```

In the consumer routine just add an `if` statement:

```python
import asyncio
import websockets
import killer

async def handler(websocket):
    while True:
        message = await websocket.recv()
        await consumer(message)
        if killer.kill_now():
            break

async def hello():
    async with websockets.connect('ws://localhost:8765') as websocket:
        ... subscribe to some websocket server ...
        await handler(websocket)

asyncio.get_event_loop().run_until_complete(hello())
```

**Comment by cjerdonek** [comment]
I would be in favor of a description or example of proper handling as well (e.g. if there are any gotchas, etc). Thanks for a great project, @aaugustin!

**Comment by cjerdonek** [comment]
By the way, it looks like there is a more "native" way of handling signals that is described [here](https://docs.python.org/3/library/asyncio-eventloop.html#set-signal-handlers-for-sigint-and-sigterm) in the asyncio docs (at least for UNIX).

**Comment by aaugustin** [comment]
That example shuts down the event loop immediately.

If you want to do something more graceful, you can call `add_signal_handler` to register a handler that will set a Future and have your own logic exit when that Future is set.

I could document that.

**Comment by Badg** [comment]
Quick warning, since I had the distinct "pleasure" of dealing with cross-platform signal handling recently, is that (generally speaking) signal handlers on Windows don't exactly work. Unless originating from a daughter/parent process, they just cause the Python interpreter to immediately die, with no cleanup whatsoever. So if ``add_signal_handler`` gets doc'd, it might be worthwhile to mention compatibility issues (though, I suppose that may be implied, given that ``add_signal_handler`` is unix only).

**Comment by aaugustin** [comment]
I haven't had that pleasure but I know that signals don't work (well) on Windows (with Python).

Honestly my preference would be a cop-out: point to someone else's documentation on this matter. It's the general problem of stopping properly an asyncio-based server; I don't think websockets requires anything specific.

**Comment by byxor** [comment]
> If you want to do something more graceful, you can call add_signal_handler to register a handler that will set a Future and have your own logic exit when that Future is set.

This unfortunately only works from the main thread. I've been trying to write a simple wrapper around websockets that runs on its own thread, but can't add any signal handlers because a RuntimeError is raised:

`RuntimeError: set_wakeup_fd only works in main thread`

**Comment by aaugustin** [comment]
This doesn't appear to be specific to websockets. Any asyncio program could have the same problem.

You're likely to get more answers if you frame this as an asyncio issue. I'm not sure where is the best place to ask such questions.

**Comment by Badg** [comment]
It's actually not just a problem with asyncio, but with signal handling in Python in general. All signal handling in Python happens in the main thread, regardless of application or operating system.

@byxor your best option is going to be:

1. define a dedicated signal handling coroutine/function that does whatever you want it to
2. write a signal handler **function** that invokes that coro or function via ```loop.run_coroutine_threadsafe``` or ```loop.call_soon_threadsafe``` (respectively)
3. register that handler using ```signal.signal``` directly.

Be aware that, like asyncio signal handling, this is essentially unix-only. Technically this will also work from Windows, but in practical reality (unless you use something like daemoniker instead of ```signal.signal```) any signal you send from a separate process will result in immediate shutdown with no cleanup or signal handling on Windows.

Also, be super careful combining threading with asyncio. Asyncio docs aren't great in this area and it can be extremely finicky to get right. If you want some code examples, check out the source for [loopa](https://github.com/Muterra/py_loopa), but be warned that it's is still very much a moving target. In particular, I think [core.ManagedTask](https://github.com/Muterra/py_loopa/blob/master/loopa/core.py#L97) and most of [utils](https://github.com/Muterra/py_loopa/blob/master/loopa/utils.py) might be decent reference material; utils in particular has several examples of how tricky it is to get threadsafe asyncio operations to work. Almost everything has to be piped through ```call_soon_threadsafe``` and ```run_coroutine_threadsafe```.

**Comment by aaugustin** [comment]
The documentation should probably say something about this, if only to point to the right location. It's a common question.
