### ISSUE TITLE
Use ensure_future in server examples

### ISSUE THREAD

**Issue by bcb** [aaugustin/websockets#130]
The [examples](https://websockets.readthedocs.io/en/stable/intro.html) use two run commands:

``` python
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

If the purpose of the first one is only to add the task to the loop, would it not be better to use `ensure_future`?

``` python
asyncio.ensure_future(start_server)
asyncio.get_event_loop().run_forever()
```

**Comment by aaugustin** [comment]
In non-toy use cases, you'll need the result value of `start_server` to stop the server.

```
server = asyncio.get_event_loop().run_until_complete(start_server)
try:
    asyncio.get_event_loop().run_forever()
# still a toy, a real program would do this with signals.
except KeyboardInterrupt:
   server.close()
   asyncio.get_event_loop().run_until_complete(server.wait_close)
```

(not 100% sure about that code, I just typed it from memory, but hopefully you get the idea)

I'm going to keep this ticket around because it's a valid question that the docs should address, one way or another.

**Comment by bcb** [comment]
That makes sense. I wasn't aware of the need to clean up. Seems like the ideal case for a context manager. Going to add to that discussion (#86).

**Comment by aaugustin** [comment]
This may deserve some documentation as well.

**Comment by aaugustin** [comment]
I added a full example of how to shut down the server.
