### ISSUE TITLE
conda package now available

### ISSUE THREAD

**Issue by scopatz** [aaugustin/websockets#151]
There is now a conda package for websockets available at https://anaconda.org/conda-forge/websockets It would be nice if this made it into the documentation somewhere. Thanks!

**Comment by aaugustin** [comment]
Thanks for the suggestion. Unfortunately I'm not sure I want to do that.

Documenting these conda packages would imply they're supported. However, since I know very little about conda and have no control on how packages are created and updated, I couldn't do anything if someone runs into issues.

I looked at how other projects handle this. There are Conda packages for Django but they aren't mentioned in the (very extensive) documentation of Django. I'm confortable following that lead.

Generally speaking I don't think it's a common practice for open-source projects to list all their downstream distributors.

**Comment by scopatz** [comment]
Thanks for the fast response.

> have no control on how packages are created and updated, I couldn't do anything if someone runs into issues.

In fact, the entirety of this package is maintained by the repo https://github.com/conda-forge/websockets-feedstock. We'd be happy to have you as a maintainer of that repo, if your are interested. Or even if you are not, you are always welcome to submit a PR against this repo.

> Generally speaking I don't think it's a common practice for open-source projects to list all their downstream distributors.

I think this varies from project to project and I saw that you had pypi listed. In any event, I though you'd like to know that it is available. Thanks for the consideration.

**Comment by aaugustin** [comment]
PyPI is the upstream in this case. That's the only place where you can find a release.

**Comment by scopatz** [comment]
Just so you know, we grab releases from the tag on github.

**Comment by aaugustin** [comment]
Hmm. Yeah. This isn't intended. Whatever works.
