### ISSUE TITLE
Non-determistically fails to run the tests suite due to unreliable timing in tests

### ISSUE THREAD

**Issue by sandrotosi** [aaugustin/websockets#163]
Hello,
as reported in Debian as https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=854335

```
python-websockets's testsuite appears to use method timing/benchmarking in such a way that it will non-deterministically FTBFS:

  […]
  
  ======================================================================
  FAIL: test_eof_received_timeout (websockets.test_protocol.ClientTests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/build/1st/python-websockets-3.2/.pybuild/pythonX.Y_3.5/build/websockets/test_protocol.py", line 792, in test_eof_received_timeout
      self.loop.run_until_complete(self.protocol.close(reason='close'))
    File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
      next(self.gen)
    File "/build/1st/python-websockets-3.2/.pybuild/pythonX.Y_3.5/build/websockets/test_protocol.py", line 249, in assertCompletesWithin
      dt, max_time, "Too slow: {} >= {}".format(dt, max_time))
  AssertionError: 0.022619478404521942 not less than 0.019 : Too slow: 0.022619478404521942 >= 0.019
  
  ======================================================================
  FAIL: test_remote_close_race_with_failing_connection (websockets.test_protocol.ClientTests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/build/1st/python-websockets-3.2/.pybuild/pythonX.Y_3.5/build/websockets/test_protocol.py", line 716, in test_remote_close_race_with_failing_connection
      self.assertConnectionClosed(1011, '')
    File "/build/1st/python-websockets-3.2/.pybuild/pythonX.Y_3.5/build/websockets/test_protocol.py", line 237, in assertConnectionClosed
      self.assertEqual(self.protocol.close_code, code)
  AssertionError: 1000 != 1011
  
  ======================================================================
  FAIL: test_close_handshake_timeout (websockets.test_protocol.ServerTests)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "/build/1st/python-websockets-3.2/.pybuild/pythonX.Y_3.5/build/websockets/test_protocol.py", line 761, in test_close_handshake_timeout
      self.loop.run_until_complete(self.protocol.close(reason='close'))
    File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
      next(self.gen)
    File "/build/1st/python-websockets-3.2/.pybuild/pythonX.Y_3.5/build/websockets/test_protocol.py", line 249, in assertCompletesWithin
      dt, max_time, "Too slow: {} >= {}".format(dt, max_time))
  AssertionError: 0.0209119264036417 not less than 0.019 : Too slow: 0.0209119264036417 >= 0.019
  
  ----------------------------------------------------------------------
  Ran 235 tests in 2.067s
  
  FAILED (failures=3, skipped=29)
```

maybe these kind of benchmarking tests shouldnt be part of the tests suite, or they should not report errors if they are slower than expected? in the case of the reported failure, we know the package was built on a very busy machine, so it is possible that influenced.

please be aware that this issue, if unresolved, would prevent websocket to be part of the upcoming debian release (codename stretch), so could you please have a look at it soon?

thanks!

**Comment by RemiCardona** [comment]
Maybe we can use http://asynctest.readthedocs.io/en/latest/asynctest.case.html#asynctest.ClockedTestCase to reliably test timeouts? I haven't tried it in any of the code I'm working on, so I'm not 100% sure it'll help.

**Comment by aaugustin** [comment]
To be honest, if Debian doesn't package websockets, for me that means fewer users stuck for years on an obsolete version and an easier life as a maintainer, so that's a strong argument in favor of not helping.

Also it's incorrect to describe these tests as benchmarking tests. They are conformance tests. They check that events happen in the correct order and that timeouts are handled correctly.

On a more constructive note, `export WEBSOCKETS_TESTS_TIMEOUT_FACTOR=100` before running tests should prevent this issue. Most likely 10 is enough, but if your build server swaps a lot, 100 is safer. You may have to go up to 1000 if the build servers can be unresponsive for seconds. Most likely you don't care if the test suite takes a couple minutes to execute, most of which will be spent idling, waiting for timeouts.

I care a lot about a fast test suite during development and the default settings are optimized for this use case. I knew other people would make different tradeoffs and that's why I implemented this configuration parameter.

If this resolution isn't satisfactory, you can add a Debian patch to skip these tests. If they didn't exist you'd build the package anyway -- I don't think you audited test coverage, did you? — so it shouldn't be a big deal to skip them if you can't run them reliably on your build infrastructure.

**Comment by aaugustin** [comment]
@RemiCardona That's interesting but I'd like to avoid dependencies as long as there isn't a compelling reason to add one.

I believe this issue doesn't cross the "compelling" threshold because have an adequate workaround or can find one here. For example we can add a WEBSOCKETS_TESTS_SLOW_SERVER env variable that skips timing sensitive tests for users that have really slow test servers (more than 10-100x slower than CPUs produced in the last five years).
