### ISSUE TITLE
sharing global state

### ISSUE THREAD

**Issue by noahdesu** [aaugustin/websockets#164]
what would be the preferred method for sharing global state such as a database connection or shared queue of work items among all active websocket connections?

**Comment by aaugustin** [comment]
This is entirely up to you! `websockets` has no opinion on that.

It also depends a lot on your context. If you expect a single process to suffice, you can use an in-memory asyncio.Queue for your work items. If you need multiple processes to handle your work load, then you need a shared system with which your websockets servers communicate.

Usually it's a good idea to keep your network server (the websockets process) as lean as possible in order to scale as far as possible with a single process. You can't underestimate the benefits in terms of simplicity.

Of course, if you're building for 10M concurrent users, it's a different story. Then you obviously need multiple processes (but if that were the case I think you'd frame your question differently).
