### ISSUE TITLE
Can this be used without async/await?

### ISSUE THREAD

**Issue by roman-ku** [aaugustin/websockets#173]
I tried removing the async/await and got this error:

    with websockets.connect('...') as websocket:
    AttributeError: __exit__

**Comment by qwexvf** [comment]
@roman-ku since it is based on asyncio you can't use without async/await....
why are you trying to remove them ?

**Comment by aaugustin** [comment]
Yes, you can use websockets without `async` / `await`. You'll have to use `@asyncio.coroutine` and `yield from` instead. This is generally less convenient than `async` / `await`. The only reason I can think of for doing that is if you're stuck on Python 3.3 (which is uncommon, since major distros ship 3.4)

If your question really was "can I use websockets in a synchronously", as @qwexvf correctly points out, websockets isn't a good choice for you. In that case, I suggest using another library, as websockets is a very small library whose sole purpose is to provide a convenient asynchronous API.

**Comment by roman-ku** [comment]
@aaugustin @qwexvf 

Yes my question was, can I use websockets synchronously. I need the response from the server before doing more stuff.

Alright thanks guys. I'll look for a different library.

**Comment by michaelschem** [comment]
Is there another library to use websockets synchronously?

**Comment by aaugustin** [comment]
I'm not super familiar with the landscape of other libraries.

Since this issue was filed, I started working on a solution to this problem, see #885.
