### ISSUE TITLE
<class 'websockets.py35.server.Serve'> breaks documentation and API

### ISSUE THREAD

**Issue by SlightlyCyborg** [aaugustin/websockets#291]
https://websockets.readthedocs.io/en/stable/api.html#websockets.server.serve

This link states that websockets.serve() returns a WebSocketServer, however it returns a Serve wrapper with self.server as the actual WebSocketServer

https://github.com/aaugustin/websockets/blob/master/websockets/py35/server.py#L9

**Comment by cjerdonek** [comment]
It seems (untested) like this would be solved if the `__aenter__()` and `__aexit__()` methods were put directly on `WebSocketServer` instead of creating a new wrapper class.

**Comment by condemil** [comment]
I am gonna check that out

**Comment by condemil** [comment]
I checked the solution from @cjerdonek, it looks like `async with` syntax expects `__aenter__()` and `__aexit__()` on `serve`, not on `WebSocketServer` returned by `serve`.

**Comment by cjerdonek** [comment]
I don’t think that makes sense because serve is  a function, and that’s not
how it currently works. It just needs to be on the object returned by the
function (which can be a WebSocketServer object instead of an object with
type the Server wrapper class).

**Comment by condemil** [comment]
@cjerdonek `serve` is a coroutine and that is why it cannot pass back `WebSocketServer` without being await'ed first.

**Comment by cjerdonek** [comment]
On second thought, it doesn't seem like there's a bug here at all.

When the documentation says `serve()` "returns a `WebSocketServer` object," that implicitly means after awaiting. The OP is getting a `Serve` object because the function isn't being awaited. This isn't unique to the "py35" code path. In Python < 3.5, you won't get a `WebSocketServer` object either if you don't await. You'll get a "serve generator object" (i.e. generator-based coroutine).

Perhaps what can be improved in the docs is to say that `serve()` is a coroutine. This is partly an issue with the Sphinx formatting of coroutines. There's been various discussion about how to format coroutines in Python docs. For example, here's the start of one thread:
https://mail.python.org/pipermail/async-sig/2017-June/000316.html

**Comment by cjerdonek** [comment]
Also, just for comparison, if you look at the [`create_server()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.create_server) docs (which `serve()` wraps and which the `serve()` docs link to), you'll see that it says `create_server()` "Return[s] a Server object," even though you need to await to get that returned object.

**Comment by condemil** [comment]
The issue that @SlightlyCyborg shared is about inconsistent behaviour of `serve` function, in case you use it as asynchronous context manager it returns `websockets.py35.server. Serve` wrapper instead of `WebSocketServer` object that you expect. When you use it directly (not though asynchronous context manager) it returns `WebSocketServer` object as expected.

**Comment by cjerdonek** [comment]
It returns a `WebSocketServer` in both cases when I test:

```python
async def run():
    server = await websockets.serve(lambda ws, uri: None, '0.0.0.0', 8001)
    print(f'awaiting directly: {server!r}')
    server.close()

    async with websockets.serve(lambda ws, uri: None, '0.0.0.0', 8001) as server:
        print(f'from context manager: {server!r}')
```

    # Outputs:
    awaiting directly: <websockets.server.WebSocketServer object at 0x10c088d68>
    from context manager: <websockets.server.WebSocketServer object at 0x10c088b00>

This is also evident if you look at the `__aenter__()` and `__await__()` methods of the `Serve` class here:
https://github.com/aaugustin/websockets/blob/master/websockets/py35/server.py#L11

**Comment by condemil** [comment]
Yes, I tested it again and I see the same results. I agree with you that it not looks like an issue because `WebSocketServer` object is returned after await from coroutine.

**Comment by cjerdonek** [comment]
I do have the _feeling_ that the whole wrapping of `serve()`, etc. can be made simpler. A couple thoughts are--

1. `Serve.server` is currently being used to store two different things at two different times (one during `__init__()` and one during `__aenter__()`). They should probably be different attributes.
2. It seems like the `Serve` class could be moved to the main `server.py` and the `serve()` function could go through `Serve` for all Python versions. This would create a single code path without the need for wrapping. For Python versions below 3.5, they can simply not recognize the `__aenter__()` and `__aexit__()` methods. This is just an untested thought though, so maybe there is a reason this can't be done that I'm overlooking.

**Comment by cjerdonek** [comment]
I wrote up a PR (#294) that implements what I described in my above comment.

That PR doesn't close this issue though, because I would consider the current issue a documentation one (see my comment [here](https://github.com/aaugustin/websockets/issues/291#issuecomment-337836400) on that).

**Comment by aaugustin** [comment]
Closing in favor of #294 and #295, which appear to cover the outcomes of this discussion. Thanks!

**Comment by cjerdonek** [comment]
That sounds good. My only suggestion is that in addition to #294 and #295, `serve()` should still in the short term be documented as being a coroutine. That doesn't seem to be currently stated, which may have caused confusion leading to this issue.

**Comment by aaugustin** [comment]
I made that change in 2c0b6618a71453cf1ff39a3bf769081a25475aaf.
