### ISSUE TITLE
Send notifications in coroutine

### ISSUE THREAD

**Issue by pgrandinetti** [aaugustin/websockets#336]
Following your docs I'd like to create an object that listen to a socket within an async routing and then passes the received message to other objects. For example:

```
class WSClient():

    async def listen_forever(self):
        async with websockets.connect(self.url) as ws:
            while True:
                try:
                    reply = await asyncio.wait_for(ws.recv(), timeout=10)
                except:
                    # handle things                
                # if reply was received then pass it through, e.g.
                # say self.observers is a list of objects
                for obj in self.observers:
                    obj.notify(self, reply)
```
Somewhere else in my program (let's say in the main thread) I'd like to do something like the following

```
obj = Obj() # some custom class
client = WSClient(url)
client.register(obj) # assume this is implemented in WSClient class
                     #basically it adds obj to client.observers list
client.listen_forever() # ?? - client should start in a different thread
# continue main program, do other things with obj, while client is listening
```
First of all, is this scheme feasible in the `websockets` architecture? I am not sure whether this falls into the "coroutine" or in the "callback" scenario (I am citing your docs).
And, if yes, I will then need to run the `WSClient.listen_forever` in a separate thread, but what's the best way to do so?
Thanks a lot!

**Comment by aaugustin** [comment]
Yes, this seems like a reasonable thing to do with websockets.

http://websockets.readthedocs.io/en/stable/intro.html?highlight=registration#registration may help.

Rather than using a separate thread, did you consider running an asyncio task? I wouldn't recommend mixing threads and coroutines/tasks until you're CPU-bound — and even then it's usually a better idea to use separate processes than threads.
