### ISSUE TITLE
Having trouble mocking websockets under python 3.5/36

### ISSUE THREAD

**Issue by mdear** [aaugustin/websockets#359]
I am having trouble mocking websockets, which I was able to do under python34 but breaks in python 35/36.

I am double-raising an issue, since I'm not sure if the resolution is on the asynctest side or the websockets side.

https://github.com/Martiusweb/asynctest/issues/84

**Comment by RemiCardona** [comment]
Here's what I do, and it works with asynctest 0.11+ and websockets 4.0

```python

class WebsocketProtocol(unittest.mock.Mock):
    def __await__(self):
        return self
        yield None  # pylint: disable=unreachable

class TC(asynctest.TestCase):
    def test_method(self):
        protocol = WebsocketProtocol()
        with asynctest.patch('websockets.connect', return_value=protocol) as connect_mock:
            # do stuff here
```

The `__await__` method on the mocked protocol class is the secret sauce for python 3.5+ to get the await/async to work. It's not needed in 3.4.

Basically, the mere presence of the `yield` keyword turns the function into a generator at parse time. At run time, the generator exits immediately and returns its mocked self for consumption by your tested code.

HTH

**Comment by aaugustin** [comment]
@RemiCardona Do you think it would be useful to refactor (some of) websockets' tests to take advantage of `asynctest`?

**Comment by RemiCardona** [comment]
@aaugustin we've been using asynctest for a while and I have mixed feelings about it:
`+` it generally works, allowed us to remove a lot of bespoke asyncio+unittest code (not unlike the one in websockets' tests ;) )
`+` it has a time-controlled loop which looks like a gift from the gods…
`-` … but I haven't tried it yet so no comment on its value
`-` the documentation lacks simple and straightforward examples
`-` no proper `async`/`await` support, hence my eye-hemorrhage-inducing code above
`-` every other minor release breaks our tests due to subtle semantic changes

That last one is my most recent and frequent gripe with asynctest but then again, the core (c)python APIs for asyncio/coroutines/awaitables/`yield from`/… is all over the place if you want to support 3.4, 3.5 and 3.6. So I'm not blaming asynctest folks (too much) here. But using asynctest _does_ have a maintenance cost in my experience.

My 2¢ :)

**Comment by cjerdonek** [comment]
I do think the tests should be refactored as there is currently a lot of repetition, etc. However, I don't think a third-party library is needed. In my experience, it's enough to define a few light-weight test decorators. That also gives you the advantage of finer control without the disadvantages of a dependency.

My PR [here](https://github.com/aaugustin/websockets/pull/310) adds one test starting towards what I'd recommend, and my comment [here](https://github.com/aaugustin/websockets/issues/309#issuecomment-343540863) provides a bit more explanation of the approach.

**Comment by mdear** [comment]
Thanks, @RemiCardona, with your suggestion (and a patch to asynctest) I was able to get my tests passing.   I will follow up with the asynctest folks to drive a fix forward on their end.

**Comment by Martiusweb** [comment]
Hi @RemiCardona,

Thanks for your inputs on asynctest. The lack of doc and instabilities are the main issue I'd like to solve.

Fixing the documentation is trivial but requires time (I can only work on asynctest on my spare time since more than one year).

But I need help to fix the unstable releases as I don't receive much feedback from users. In particular, no one really tests the master branch of asynctest, and breakages are always noticed after the release. I'd be very happy to test the latest commits of asynctest against your projects.

About the missing support of async/await, I'm not sure what exactly is missing so maybe we can discuss that in the issues tracker of asynctest :)

(Sorry for the noise on this ticket)
