### ISSUE TITLE
Correct form of closing the connection from the server

### ISSUE THREAD

**Issue by realcr** [aaugustin/websockets#41]
Hi. I'm running a websockets server. I was wondering **what is the correct form of closing the connection from the server.**
I include here the relevant part of my code:

    @asyncio.coroutine
    def ws_serve(self,websocket,path):
        """
        Maintains a websocket connection.
        """
        logging.info('Handling a new websocket connection')
        # Generate a new Authenticator class:
        at = Authenticator(websocket,path)

        while True:
            # Read a wrapped message from the websocket:
            wmsg = yield from websocket.recv()
            if wmsg is None:
                # Remote connection was closed.
                break

            # Handle the message at the Authenticator Class:
            yield from at.recv_msg(wmsg)

    if __name__ == '__main__':
        logging.info('Starting websocket server')
        start_server = websockets.serve(ws_serve,'localhost',8765)
        eloop = asyncio.get_event_loop()
        eloop.run_until_complete(start_server)
        eloop.run_forever()

I thought about a few options to close the connection from the server:

1. Having at.recv_msg return a value, and check that value inside the ws_serve coroutine. The cons of this idea is that the point where I decide to close the server might be somewhere pretty deep inside Authenticator.

2. Raising some special exception inside the Authenticator class. This exception will propagate all the way from somewhere inside Authenticator to ws_serve, and the infinite loop at ws_serve will terminate.

I'm pretty new to asyncio, so there might be some design idea that I'm missing. Do you have any other ideas to solve this?

p.s. This won't be complete by saying how much I appreciate the work put into building this library. It really makes my life easier. Thank you :)

**Comment by aaugustin** [comment]
Since `websockets` takes care of closing the connection when `ws_serve` returns, there's nothing specific to asyncio here. All you need is to exit `ws_serve` one way or another.

You can use either a special return value, like `None` or an exception for this purpose. Both techniques are acceptable. An exception will require less code, since you don't have to handle it in every function and I understand you have a deep call stack. However control flow with exceptions can get messy. So it's really a matter of style.
