### ISSUE TITLE
Silent import failure in tests

### ISSUE THREAD

**Issue by aaugustin** [aaugustin/websockets#415]
Cf. https://github.com/aaugustin/websockets/issues/405#issuecomment-391818096

(I'm creating this issue to make sure I don't lose track of that comment.)

**Comment by cjerdonek** [comment]
It’s not a test failure. It’s a case of something working for the wrong reason and masking an issue IIRC.

**Comment by cjerdonek** [comment]
The issue I was originally mentioning is that there is a circular import here, which doesn't seem like a good pattern to rely on:
https://github.com/aaugustin/websockets/blob/6f8f1c877744623f0a5df5917a85b97807bfb7e5/websockets/py36/_test_client_server.py#L10

But it won't be noticed because the exception is being swallowed.

For example, if you change the bottom of `test_client_server.py` to this--

```python
try:
    from .py36._test_client_server import AsyncIteratorTests            # noqa
except (SyntaxError, ImportError) as exc:                          # pragma: no cover
    print(repr(exc))
    pass
```

you can see the error by running--

```
$ python -m unittest websockets.py36._test_client_server
ImportError("cannot import name 'AsyncIteratorTests'",)
..
----------------------------------------------------------------------
Ran 2 tests in 0.012s

OK
```

The `except` clause is catching import errors other than those due to the Python version. It's probably best to refactor `get_server_uri()` into a separate module to avoid the circular import.

On a separate but related note, if `_test_client_server.py` e.g. has a bad import, the tests won't catch it because of this. For example, try putting `import foo` at the top of `_test_client_server.py` and the tests will still pass.

**Comment by aaugustin** [comment]
Oops, I checked `AsyncAwaitTests` instead of `AsyncIteratorTests`!

**Comment by aaugustin** [comment]
If you run `python3.6 -m unittest websockets.test_client_server`, then tests run as expected, including `AsyncIteratorTests`. This falls within the circular imports that Python is able to handle.

The `websockets.py3[56]._test_client_server` modules aren't supposed to be imported directly. They're prefixed with an underscore to prevent test discovery.

That said, you have a good point: catching `(SyntaxError, ImportError)` could easily mask errors. I'm going to replace it with explicit version checks (which will also be faster).

**Comment by aaugustin** [comment]
Feel free to refactor `get_server_uri()` into a new module if you'd like. I didn't take the time to do it because nothing's broken right now -- just fragile. I thought I'd do it if we change imports and hit ImportError in the future.

**Comment by cjerdonek** [comment]
I believe that would also let you put the imports at the beginning of the
module, which is better practice and improves readability, etc.

**Comment by aaugustin** [comment]
Correct.

**Comment by aaugustin** [comment]
That's a circular import problem. I'm not sure why it doesn't show up in CI.

**Comment by scarabeusiv** [comment]
Commands to run the tests:
```
export WEBSOCKETS_TESTS_TIMEOUT_FACTOR=5
python3 setup.py test || :
```

I removed the true override at the end of the tests to make them fail again.
For the logs it seems one has to login in order to be able to see them :( The direct link for latest i586 is https://build.opensuse.org/package/live_build_log/devel:languages:python/python-websockets/openSUSE_Tumbleweed/i586

**Comment by scarabeusiv** [comment]
I also checked the patches we add to python and we are not patching the unittest behaviour.

**Comment by aaugustin** [comment]
I'm not sure what `python setup.py test` does. I never ran that.

Is it possible for you to change the test command to `python -m unittest`?

Else do you know how to make `python setup.py test` behave like `python -m unittest`?

**Comment by aaugustin** [comment]
Great. Thanks for the tip.

Let's keep issue open to consider adding support for `python setup.py test`.

**Comment by aaugustin** [comment]
@scarabeusiv You can switch back to `python setup.py test` if this is easier or more consistent with your packaging toolchain.
