### ISSUE TITLE
run server on any available port

### ISSUE THREAD

**Issue by mzhng** [aaugustin/websockets#426]
How can I run the websocket server on any available port and know the port used? For example, with other socket-based APIs, using port 0 usually works. Then if you have access to the underlying socket, you can do

```
used_port = some_high_level_object.socket.getsockname()[1]
```

to know the port it used. Is there a minimal example to do something like this using this library?

**Comment by RemiCardona** [comment]
Something like this should work (untested, adapted from a private project's test suite):
```python
server = yield from websockets.serve(your_ws_handler, port=0, **other_kwargs)
used_port = server.server.sockets[0].getsockname()[1]
```

a couple things worth mentioning:
- yes, `server.server`, that's not a typo
- the `sockets` list may contain more than one socket as asyncio/python will bind to both IPv4 and IPv6 unless instructed otherwise. So you may have to iterate through that list to find the right socket, or tell asyncio/python to only use v4 or v6 sockets by giving other kwargs to `websockets.serve()`

HTH
