### ISSUE TITLE
websockets.exceptions.ConnectionClosed in intro example

### ISSUE THREAD

**Issue by calid** [aaugustin/websockets#484]
running the intro client/server example I get the following error in the echo server:

```
Error in connection handler
Traceback (most recent call last):
  File "/home/calid/.local/lib/python3.6/site-packages/websockets/server.py", line 152, in handler
    yield from self.ws_handler(self, path)
  File "ws-echo.py", line 6, in echo
    await websocket.send(message)
  File "/home/calid/.local/lib/python3.6/site-packages/websockets/protocol.py", line 361, in send
    yield from self.ensure_open()
  File "/home/calid/.local/lib/python3.6/site-packages/websockets/protocol.py", line 512, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1000 (OK), no reason
```

Looking a little closer does the intro example even make sense?  The client will immediately exit after sending 'Hello world' and doesn't check for a reply from the server anyways.  Shouldn't this be changed to either have the server simply print the client's message (and not try to echo it back), or have the client actually hang around and listen for replies?

**Comment by aaugustin** [comment]
Juxtaposing the client and the server led you to assume they're designed to work together. That's a reasonable assumption. Unfortunately it isn't true. We can do better :-)

You have a more interesting example of a client and a server that work together here: https://websockets.readthedocs.io/en/stable/intro.html#basic-example

The client example doesn't make less or more sense that any program that prints "Hello world!" and exits without taking any input — the canonical example. Actually it does exactly that, except over a WebSocket connection.

**Comment by calid** [comment]
ah, well that would explain it.  Honestly I would just take the first few Getting Started sections and slap them verbatim at the top of the GH Readme.  They cover version gotchas, how to install, and provide a concise client/server example.  Seems like a perfect intro to me...

**Comment by aaugustin** [comment]
Well, the GitHub README and the Getting Started section of the docs have different purposes.

Given how GitHub displays the README, for all practical purposes, it's the home page for websockets. It's marketing, not training. It must help people understand what websockets is and whether it's worth trying for their use case as fast as possible. Therefore it's kept short.

The Getting Started section is for those who have decided they want to try websockets but don't know anything yet. It can be much more complete because those who start reading it already made a decision to invest time in websockets.
