### ISSUE TITLE
add on_open() and on_close() methods, similar to tornado web socket implementation?

### ISSUE THREAD

**Issue by shongololo** [aaugustin/websockets#52]
Would it be possible to add high-level on_open() and on_close() methods, similar to the web sockets implementation in Tornado, so that initialisation and cleanup can be performed?

**Comment by aaugustin** [comment]
Perhaps there's a more straightforward solution for websockets, as its API uses coroutines rather than callbacks:

    def handler(ws, path):
        do_on_open(ws)
        try:
            # handler logic.
            do_handler(ws, path)
        finally:
            do_on_close(ws)

I want the API to stay explicit. Simply by reading the code, you must be able to follow what's going on. Introducing a callback-based API would break this design principle.

Since I'm not familiar with Tornado's implementation of `websockets`, I may have failed to understand your idea. If so, could you clarify it?

**Comment by shongololo** [comment]
Hi, for now I'm using the:

   if message is None:
               break

and:

    if not websocket.open:
                break

and they are doing the trick. I understand what you are saying re: callbacks and this makes sense. Thanks.

**Comment by aaugustin** [comment]
Cool.

Let me know if you think of improvements that are compatible with this philosophy. The library is rather simple at this time. Perhaps it could support some common use cases better :-)

**Comment by shongololo** [comment]
The try / finally style works nicely for the send method. 
 
It would be nice if something similar were possible with the receive method i.e. if recieve() could throw an error that allows for activating the 'graceful exit' code through error handling rather than checking for None types?

**Comment by aaugustin** [comment]
Yes, I'm aware that this API creates some ugly code.

Unfortunately I can't change it without breaking backwards-compatibility in a way that will affect everyone :-/
