### ISSUE TITLE
Allow override for host/port parameters

### ISSUE THREAD

**Issue by Kirill888** [aaugustin/websockets#540]
What
-----

Say I want to connect to a TLS end-point, but can only do it through an a ssh tunnel

1. I'll start a tunnel like so:

```
ssh -N -L 50321:echo.websocket.org:443 ssh.jumper.host
```

2. Then connect `echo.websocket.org:443` via `localhost:50321`

```python
async with websockets.connect('wss://echo.websocket.org', 
                              host='127.0.0.1', 
                              port=50321) as websocket:
    await websocket.send('test')
    ...
```

Right now this code won't work, but I can achieve the same result by supplying connected socket and an extra `server_hostname` parameter. It is quite a bit more work and I'd rather let underlying `create_connection` code setup socket of its own.

Other use-case is supplying IP address of a server, a kind of in app DNS caching.

How
----

It doesn't look like this requires many changes. I have prototyped this here: https://github.com/Kirill888/websockets/commit/a9f8846c7958dfabc41d3e996d47735783f2b5d8

Happy to open a PR if you are happy with such change.

**Comment by aaugustin** [comment]
The change looks reasonable.

It needs:

- tests — complexity should be somewhere between `ClientServerTests.test_basic` and `ClientServerTests.test_explicit_socket`.
- docs — unless we can argue that it's just the expected behavior of "serve is a wrapper around the event loop's create_server method."

**Comment by speedyb0y** [comment]
This is exactly what I'm trying in here.

I do have hundreds of connections and I'm using my own DNS caching so I pass f'wss://{SERVER_IP}/uri'.

But settings in the server changed and I can't do it anymore, because the server expects the hostname in the SSL handshake.

We need a "hostname" parameter on the connect() method, so it can pass that value when opening the SSL socket.

So now I have to use the hostname in the URL, and hope I'm not opening hundreds off connections to the same IP while there are 4 servers available :(
