### ISSUE TITLE
Reconnection not working after code 1006 <connection closed abnormally [internal]>, no reason

### ISSUE THREAD

**Issue by asohn123** [aaugustin/websockets#569]
Hi, 

I'm doing a private Kaggle challenge and I'm trying to get data from ~300 websockets simultaneously. I've managed to do this, but usually the data collection process crashes after 30 hours and displays the 1006 code. I want my application to reconnect as soon as it crashes, but it never triggers the "ensure_open" statement and crashes permanently. I'm running Python 3.7 and Websockets 7.0. Any help would be greatly appreciated, thanks!

```
async def fetch_rock(rock):
    web_loc = 'wss://example:8888/ws/'
    websocket = await websockets.connect(web_loc)

    filename = './rock_data/' + rock + '.csv'
    with open(filename, 'a+') as csvfile:
        csvw = csv.writer(csvfile, delimiter=',', quotechar='|', quoting=csv.QUOTE_MINIMAL)
        while True:
            if not websocket.ensure_open():
                print('Reconnecting')
                websocket = await websockets.connect(web_loc)
            else:
                resp = await websocket.recv()
                data = json.loads(resp)

asyncio.run(fetch_rock(rock))

```

**Comment by aaugustin** [comment]
`ensure_open` isn't a public API. With the current implementation, `not websocket.ensure_open()` will always evaluate to `False`. However this is irrelevant because you shouldn't be using a private API anyway.

Using the documented, public API should give better results: https://websockets.readthedocs.io/en/stable/api.html#websockets.protocol.WebSocketCommonProtocol.open

Could you explain how you ended up trying `ensure_open`? If I can fix whatever led you on the wrong path, I'd like to.

**Comment by asohn123** [comment]
Hi @aaugustin I actually started out with .open instead of .ensure_open(). When I realized it wasn't working, I looked at the error, the last line said "line 658, in ensure_open ) from self.transfer_data_exc" and decided to try out ensure_open. Long story short, both do not work for me.

**Comment by aaugustin** [comment]
That's because you aren't catching exceptions in `recv()`.

When `recv()` raises `ConnectionClosed`, the code exits the `while True` loop.
