### ISSUE TITLE
Poor server performance on raspberry pi

### ISSUE THREAD

**Issue by Coimbra1984** [aaugustin/websockets#660]
Hi,

I'm profiling a simple websocket server on a raspberry pi 3B+.
iperf3 shows a possible througput of ~300Mbits/s. However if I setup a simple server like this:

```
import asyncio
import websockets
import numpy

async def serve(ws, path):
    blob = numpy.random.randint(0,255,size=100000,dtype=numpy.uint8)
    blob = blob.tobytes()
    while True:
        await ws.send(blob)

start_server = websockets.serve(serve, "0.0.0.0", 8765)
asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

I only get a throughput of ~18Mbits/s with a Windows10 LAN (cable) websocket client.
I see that CPU usage goes to 100% on the raspberry side (python3.5. wesockets V7.0).

If I switch sides (PC is server, raspberry is client), I do achieve a much higher throughput of ~200Mbits/s.

Is this an exepcted behaviour? Or is there a chance to get the server achieve a higher throughput?

**Comment by aaugustin** [comment]
The main different between client -> server and server -> client is that payloads are XOR'd with a random, 4 byte mask in one direction and not in the other.

Can you try `import websockets.speedups` on the RPi? If it doesn't succeed, then you need to make a compilation environment available when installing websockets so it can compile the C extension that speeds up this operation.

**Comment by Coimbra1984** [comment]
Sorry for not having responded.
I was able to `import websockets.speedups` on the RPi, but if I understand corerctly, than apply_mask is not called in my scenario.
I have a streaming server which only writes data from RPi to the client PC and if I saw the code correctly, than apply_mask is only called on server side in case of read and on client side in case of write.

Anyway I think it's okay to close the issue, I will profile the websocket code in more detail when I've time and get back to you in case of any problems.

**Comment by aaugustin** [comment]
Yes, this is correct, [masking](https://tools.ietf.org/html/rfc6455#section-5.3) happens only in the client-to-server direction. This is not the problem here.

The asymmetry shows that your example is CPU-bound on the server side — the RPi has less CPU power than the PC and the example runs slower when the RPi is the server.

I see two expensive operations on the server side:

- generating a random payload with `numpy.random.randint(0,255,size=100000,dtype=numpy.uint8)`: this shouldn't be the culprit because it happens only once when the connection is established; 
- compressing that payload: I'm betting on this one: you can disable compression with `websockets.serve(..., compression=None)` and check if it's faster

**Comment by Coimbra1984** [comment]
Okay, cool thanks for the hint. Setting `compression=None` did the trick

**Comment by aaugustin** [comment]
If you don't want to disable compression entirely, you can also try to [tweak the settings](https://websockets.readthedocs.io/en/stable/extensions.html#per-message-deflate-configuration-example). I'm not sure you'll get meaningful results, though, because settings are designed to control memory use (which is usually the bottleneck when managing hundreds of connections) rather than CPU.
