### ISSUE TITLE
mypy: Module has no attribute "connect"  [attr-defined]

### ISSUE THREAD

**Issue by antonagestam** [aaugustin/websockets#679]
As of mypy 0.730 using `no_implicit_reexport = True` errors are reported when importing names from the top-level module. I'm guessing this is due to mypy not being able infer the dynamic contents of `__all__`, and instead having relied on inferring the imports previous to 0.730.

Would you be open to a pull request that hard-codes the contents of `__all__` instead of building it dynamically from the __all__s of submodules?

**Comment by aaugustin** [comment]
I'd be open to that, with a test that checks that `assertEquals(set(websockets.__all__), set(<current definition>))`. There's no obvious place to put that test; try something; it won't be hard to change later anyway.

Ideally, I'd like to perform imports on demand, so programs that only use the client side don't load the server side needlessly and vice-versa. This will likely open a whole can of worns so it shouldn't prevent a quick improvement here.

**Comment by antonagestam** [comment]
That makes sense. I will probably be able to get something together this week.

**Comment by antonagestam** [comment]
> Ideally, I'd like to perform imports on demand, so programs that only use the client side don't load the server side needlessly and vice-versa.

Wouldn't the most straight-forward approach be to not import the submodules' contents in websockets/__init__.py? Why not just let them live under their respective namespaces? :)

**Comment by aaugustin** [comment]
Yes, that would be the most straight forward approach, if it weren't for backwards-compatibility.

I always documented the import paths as `websockets.connect` and `websockets.serve` rather than `websockets.client.connect` and `websockets.server.serve`. I did to keep things simple: just import anything you need from `websockets`.

This strategy has unfortunate consequences but I feel it's best to live with the consequences.

**Comment by antonagestam** [comment]
@aaugustin Gotcha :)
