### ISSUE TITLE
Exceptions stalling on high incoming traffic

### ISSUE THREAD

**Issue by timakro** [aaugustin/websockets#709]
I was at the start of writing a websocket client processing high amounts of incoming data from an external API when I noticed this unusual behavior. Exceptions thrown in the scope of the connection context manager after the high traffic started would cause the client to hang for 30 seconds until the client terminated and the traceback was printed. I managed to get the same behavior with a server running locally written with the websockets lib. Here's a minimal example to reproduce the problem:

Client:

```python
import asyncio
import websockets

async def hello():
    uri = "ws://localhost:8765"
    async with websockets.connect(uri) as websocket:
        raise Exception("Bug!")

asyncio.get_event_loop().run_until_complete(hello())
```

Server:

```python
import asyncio
import websockets

async def echo(websocket, path):
    while True:
        await websocket.send("flood")

start_server = websockets.serve(echo, "localhost", 8765)

asyncio.get_event_loop().run_until_complete(start_server)
asyncio.get_event_loop().run_forever()
```

Python version: 3.8.0
Result: Client hangs for 30 seconds until printing the traceback and exiting
Excepted result: Client should print the traceback and exit immediately

This is mostly a problem while developing. Imagine writing logic to parse the incoming data and having to wait 30 seconds for each test to see what mistake you've made.

**Comment by aaugustin** [comment]
That's more or less by design. The context manager doesn't exit until the connection is closed (so you know you don't leak TCP connections, asyncio tasks, etc.)

Since you're flooding the connection, there's a large backlog of data. When the client hits the exception, it sends a close frame to close the connection, but never gets the close frame from the server because there's far too much data in the pipe. Eventually the connection timeouts and websockets closes it forcefully.

Generally speaking, network connections don't work well if you clog the pipes with more data than the system can absorb. Your example, where the server sends an unlimited amount of data at maximum rate and the client never reads any of this data, isn't a realistic use case. I'm not seeing how to do much better here.

**Comment by timakro** [comment]
Thanks for the quick response!

It's interesting that I can't reproduce this behavior locally with the websockets server with more reasonable amounts of traffic while it is happening with a real API. Introducing the slightest delay in the server code from above between sending fixes the issue (which would be expected).

Although this is happening for me with a real API. Some quick measurements give 13960 messages or 1528621 bytes of data in a minute which is a lot but not unreasonable. Also there might be a backlog of data but the backlog is definitely not growing, comparing timestamps with the server the latency stays pretty constant at 0.12 seconds.
