### ISSUE TITLE
About async websocket client ?

### ISSUE THREAD

**Issue by phpmaple** [aaugustin/websockets#713]
I just confused when I need used async websocket client, and just in websocket client, because sync websocket client same to this, after every step need await

**Comment by aaugustin** [comment]
If your program contains just one client connected to one server and doesn't do anything while it's waiting for messages, then a sync WebSocket client is fine. `websockets` only provides an async client, so you'll have to find another library.

If you want to connect many clients to different servers in the same program, or if you want to run many other tasks in parallel, then an async client is useful. (I say "many" because threads are usually fine for "a few".)

**Comment by phpmaple** [comment]
Thank you for your response
