### ISSUE TITLE
relation of ping_interval with ping_timeout

### ISSUE THREAD

**Issue by adriansev** [aaugustin/websockets#719]
Hi! Is there (or is it required) any relation between ping_interval and ping_timeout?
If i have a ping_interval of 10 and ping_timeout of 20 are the pongs strictly linked to the ping that was send, so if the ping_timeout is reached, is for the ping from 20s ago?
Is there any recommendation about this? (like keep them the same size?)
Thank you!

**Comment by lgrahl** [comment]
Yes, Pongs are associated to a ping by a random payload that is being echoed.

There's no recommendation other than what makes sense for your use case. It probably makes sense to keep `pong_timeout` smaller than the TCP timeout. :slightly_smiling_face: Most use cases I've seen use it to do early connection loss detection because TCP timeouts can be very long.

**Comment by adriansev** [comment]
Thank you!
