### ISSUE TITLE
WebSocketCommonProtocol: max_size and None

### ISSUE THREAD

**Issue by aldur** [aaugustin/websockets#75]
From the `WebSocketCommonProtocol` docs:
> The ``max_size`` parameter enforces the maximum size for incoming messages
> in bytes. The default value is 1MB. ``None`` disables the limit. If a
> message larger than the maximum size is received, :meth:`recv()` will
> return ``None`` and the connection will be closed with status code 1009.

Is there any particular reason this doesn't throw, instead, a specific exception (something like `BufferError`)?
The connection will be closed, so there is no way to use it again without re-opening it.
An exception seems more explicit to me (I myself struggled to find the reason why I was getting None on some calls).

If you agree with me I could fix the issue and send a PR :).

**Comment by aaugustin** [comment]
The convention adopted by this library since the very beginning is to return `None` when failing the connection (as defined by the websockets RFC).

Raising an exception would also be a valid design but that boat has sailed: I can't ask every use to rewrite all their connection termination handling code.

Perhaps adding some logging would help. Currently if you enable logging at the DEBUG level the cause will be immediately obvious.

**Comment by aldur** [comment]
All clear, thank you :)

**Comment by aaugustin** [comment]
I would still like to consider *additional* logging at a high level (INFO or WARNING) for some error conditions.

**Comment by aldur** [comment]
Yes I agree with a WARNING log entry and would consider an explicit documentation paragraph stating how and when enabling logging could save a possible headache.

**Comment by aaugustin** [comment]
Yes, I'll look at clarifying the documentation.

**Comment by aaugustin** [comment]
Actually I changed my mind. I'm considering changing the API of `recv()` in version 3.0. Let's follow up in #77.
