### ISSUE TITLE
max_size of messages in bytes or chars?

### ISSUE THREAD

**Issue by pembeci** [aaugustin/websockets#756]
Documentation first states:

> The max_size parameter enforces the maximum size for incoming messages in bytes.

Then for `max_queue`:

> Since Python can use up to 4 bytes of memory to represent a single character, each connection may use up to 4 * max_size * max_queue bytes of memory to store incoming messages.

but if `max_size `was already in bytes why are we multiplying with 4? We should do this if max_size was specifiying number of chars in unicode string. I am confused.

**Comment by aaugustin** [comment]
Python uses Latin-1 (1 byte / char), UCS-2 (2 bytes / char) or UCS-4 (4 bytes / char) to store strings in memory, depending on which characters the string contains.

Here's an examples of how an attacker can use this to trigger the x4 factor you're asking about.

**Size in messages**

1000 characters that UTF-8 encodes on 1 byte:

```python
>>> len(('a' * 1000).encode('utf-8'))
1000
```

Adding 1 character that UTF-8 encodes on 4 bytes:

```python
>>> len(('a' * 1000 + '𐍈').encode('utf-8'))
1004
```

**Size in memory**

1000 characters that fit in Latin-1:

```python
>>> sys.getsizeof('a' * 1000)
1049
```

That's 49 bytes for the data structure (which could be system-dependent) + 1000 bytes of content.

Adding 1 character that requires UCS-4 (because it isn't in UCS-2, let alone Latin-1):

```python
>>> sys.getsizeof('a' * 1000 + sys.getsizeof('a' * 1000 + '𐍈') - sys.getsizeof('')
4080
```

I think that's 76 bytes for the data structure + 4004 bytes of content.

There you see the x4 factor.

**Comment by aaugustin** [comment]
I'll check if I can clarify the docs.

**Comment by pembeci** [comment]
Thanks for the explanation. You don't need to get into this much details in the docs I guess. Crucial thing is how `max_size` makes its boundary check. If it is using `sys.getsizeof` on the message for instance, it seems to me that x4 is redundant. It will be already accounted for.

**Comment by pembeci** [comment]
Very useful and well thought library BTW. Thanks for it too.

**Comment by aaugustin** [comment]
> Crucial thing is how `max_size` makes its boundary check. If it is using `sys.getsizeof` on the message for instance, it seems to me that x4 is redundant. It will be already accounted for.

`max_size` is in bytes. The potential x4 factor (with messages containing UCS-4 characters) is just explained in the documentation to help users anticipate memory use.

**Comment by pembeci** [comment]
Will max_size allow a message to pass through if it is set to 100 bytes but the message contains 50 UCS-4 characters?

**Comment by pembeci** [comment]
Sorry if all of this seems nitpicking but we'll listen a lot of sockets async and as you said we are trying to anticipate memory usage in case buffers fill while we process messages.

**Comment by aaugustin** [comment]
`max_size=100` will allow a message to pass though if and only if the UTF-8 encoded message is less than 100 bytes.

A message containing up to 50 UCS-4 characters may require up to 200 bytes for encoding with UTF-8.

I'd set `max_size=200` for this use case.
