### ISSUE TITLE
Can create_proto be a callable in websockets.client.connect

### ISSUE THREAD

**Issue by finkandreas** [aaugustin/websockets#764]
I'm currently playing with websockets and I'm a little bit confused about the `create_proto` parameter to `websockets.client.client`. On the website it is mentioned that it can be a Callable which returns a WebSocketClientProtocol, so I thought that his function definition should be fine:
```
def _make_proto(self, *, origin: Optional[websockets.Origin],
              extensions: Optional[Sequence[websockets.extensions.base.ClientExtensionFactory]],
              subprotocols: Optional[Sequence[websockets.Subprotocol]],
              extra_headers: websockets.http.HeadersLike,
              **kwargs: Any) -> websockets.WebSocketClientProtocol:
    # do_something
    return websockets.client.WebSocketClientProtocol(origin=origin, extensions=extensions, subprotocols=subprotocols, extra_headers=extra_headers, **kwargs)
```
and passing it like this to a connect:
```
my_websocket = await websockets.connect(my_uri, create_protocol=_make_proto)
```
This works fine, but it throws an error with mypy:
```
websocket_test.py:46: error: Argument "create_protocol" to "Connect" has incompatible type "Callable[[NamedArg(Optional[Origin], 'origin'), NamedArg(Optional[Sequence[ClientExtensionFactory]], 'extensions'), NamedArg(Optional[Sequence[Subprotocol]], 'subprotocols'), NamedArg(Union[Headers, Mapping[str, str], Iterable[Tuple[str, str]]], 'extra_headers'), KwArg(Any)], WebSocketClientProtocol]"; expected "Optional[Type[WebSocketClientProtocol]]"
```
Is it an incorrect usage of the `create_protocol` parameter or is the type annotation incomplete?

**Comment by aaugustin** [comment]
It's really (like really really) hard to get mypy to deal with websockets APIs because mypy doesn't support async all that well and because websockets APIs are quite complex: `connect` is a class, a "coroutine-like" and an async context manager at the same time.

The current type annotations are the result of a lot of shotgun debugging (and contributing fixes to mypy, and getting regressions on theses fixes in later releases...) I'll see if I can do something but don't get your hopes too high, unfortunately :-(
