### ISSUE TITLE
Some attributes not initialized in WebSocketCommonProtocol

### ISSUE THREAD

**Issue by cjerdonek** [aaugustin/websockets#767]
I had some code that was working prior to 8.0 that stopped working when upgrading. When a connection ended, the code did some debug logging like logging `protocol.close_code`. Starting with 8.0, that code started raising `AttributeError` because the attribute (along with some others) aren't initialized starting with 8.0:
https://github.com/aaugustin/websockets/commit/94945fec3280c1c6d04aa4c9dc41a794f1ef1a42#diff-5e2d99fc26f0a3387bd0ff4241906a9bL225-R240
The changelog also doesn't mention that these attributes would be going away. Some of the other attributes affected are `path` and `request_headers`. Is there a reason the attributes can't all be initialized to some value like `None`, or an equivalent for the attribute's type?

**Comment by aaugustin** [comment]
If you initialize them to None, type declarations become more complicated.

This mypy experiment is a complete disaster.

**Comment by cjerdonek** [comment]
Are you sure? For example, what about initializing `close_code` to 0? It seems like the type checker would be just as happy with that.

**Comment by aaugustin** [comment]
Yes, the type checker would be happy with that, but I wouldn't. The close code is undefined until we receive a close frame (or until we decide we'll never receive one because the connection has dropped). Usually undefined values are set to None in Python. That's what websockets used to do.

In order to avoid a bunch of `Optional[...]` I opted not to define the at all until we know the value. That was probably a mistake.

There's an easy, but ugly, way to restore backwards-compatibility: rename `close_code` to `_close_code` and add:

```python
    @property
    def close_code(self):
        return getattr(self, `_close_code`, None)
```

The alternative is to bite the bullet, use `Optional[None]` and add whatever needed for mypy to stop complaining. This may be feasible; I don't think I tried very hard.

**Comment by aaugustin** [comment]
`close_reason` has the same problem and should be treated similarly to `close_code`.

Ditto for all other public attributes that are in the same situation.

I don't think we have to make changes for the private attributes.

**Comment by cjerdonek** [comment]
Okay, I wasn't sure if it was the Optional you were trying to avoid. I agree mypy doesn't necessarily make things easy. I think it's probably just a lot harder when trying to do it all at once as opposed to incrementally, where you can address these things at a slower pace.

**Comment by aaugustin** [comment]
If the Sans I/O refactor completes, all these will become properties of the asyncio Protocol, forwarded to the underlying Sans I/O Connection. This will provide an easy opportunity to use getattr to provide a default value. I guess you'll have worked around the issue long before we get there... but at least that's a plan.

**Comment by aaugustin** [comment]
It's fixed in the main branch for `close_code` and `code_reason`.

`path`, `request_headers` and `response_headers` are always set before it makes sense to access them. In practice, the only possible problem is that `response_headers` isn't set in `process_request` and `select_subprotocol`, but it doesn't make sense to access it at this point anyway as the response headers aren't defined yet.

So, for practical purposes, this bug is fixed.
