### ISSUE TITLE
Why do docs show 'await server.close()' if close() is not awaitable?

### ISSUE THREAD

**Issue by chmedly** [aaugustin/websockets#774]
My question/report here springs from my question on Stack Overflow. [Start and Stop Server?](https://stackoverflow.com/questions/62205620/asyncio-how-can-i-stop-and-restart-server-without-stopping-event-loop?noredirect=1#comment110127484_62205620)
I find that awaiting `server.close()` throw an error.  And awaiting `server.wait_closed()` never returns.  

I can't seem to figure out how to cause the code to block until the server is officially closed.  
And revisiting the websockets documentation doesn't clear this up.

**Comment by aaugustin** [comment]
Why not do what the documentation recommends? https://websockets.readthedocs.io/en/stable/deployment.html#graceful-shutdown

Then, if you don't want to stop the event loop, instead of:

```python
loop.run_until_complete(echo_server(stop))
```

do:

```python
loop.create_task(anothertask)
loop.run_forever()
```

**Comment by aaugustin** [comment]
Then your `anothertask` can:

- stop the server at any time with `stop.set_result(None)`
- restart the server by re-running `stop = loop.create_future(); loop.create_task(echo_server(stop))`

You can drop the signal listener if you don't need it.

**Comment by chmedly** [comment]
Honestly, I think I misinterpreted the "Graceful Shutdown" section on one of my first reads through and just mentally jumped past it on subsequent reads. The async language `async with websockets.serve...` is the important part I was missing. I'm certainly getting hung up by the mix of old, older and recent async language. 

I'm curious what you think of my answer to the SO question. I think I'm using the most recent Python async recommendations. Calling "run" on the main() function appears to be the most recommended way to initiate async code now and this bit of code feels much simpler than the async messes I've tried with other approaches. 

Thank you for your help. But what about the question of this issue? I guess I have 2 questions. Why is close() shown with the word 'await' in front of it in the documentation?  And why am I not able to get a return while awaiting `server.wait_closed()`?

**Comment by aaugustin** [comment]
> Why is close() shown with the word 'await' in front of it in the documentation?

The close method of the `WebSocketServer` class is shown without `await` in front of it in the documentation: https://websockets.readthedocs.io/en/stable/api.html#websockets.server.WebSocketServer.close

The close method of the `WebSocketServerProtocol` class is a coroutine. Perhaps that's where you saw the `await` keyword?

> And why am I not able to get a return while awaiting server.wait_closed()?

I don't know. `async with websockets.serve(...)` eventually calls `wait_closed()`, so if that works, then `wait_closed()` works.

**Comment by WarrenGandy** [comment]
> The close method of the WebSocketServerProtocol class is a coroutine. Perhaps that's where you saw the await keyword?

Oh dear.  Yes, I think I was looking at the wrong section.  Ok, mystery solved on that.

Now the issue of wait_closed...  It seems that this is probably a moot question since a) it's not a recommended way of writing asyncio code anymore.   b) I've revisited my test code and I'm not having a problem with wait_closed() blocking indefinitely like was before.  

b) continued..  I'm using this [code](https://pastebin.com/GQ6KMK81) except that I uncommented the wait_closed line and added 'await' to the front so it looks like this: `await server.wait_closed()` Just now, it's clearing it just fine. I've been bouncing between 3 different computers while working with this. Perhaps my experience with this issue earlier was because of something in the environment of one of these machines. I sincerely apologize if that is the case... 

Lastly, I've written up a [version](https://pastebin.com/N8t3HPpn) of this "color_server" using your suggestion to `async with websockets.serve()`.  I implemented the multiple simultaneous servers with an extra function so it's a little bit more complicated. But it seems to function just as well as the code I posted to SO. Is there any reason you might suggest one approach over the other?

**Comment by chmedly** [comment]
> The close method of the WebSocketServerProtocol class is a coroutine. Perhaps that's where you saw the await keyword?

Oh dear. Yes, I think I was looking at the wrong section. Ok, mystery solved on that.

Now the issue of wait_closed... It seems that this is probably a moot question since a) it's not a recommended way of writing asyncio code anymore. b) I've revisited my test code and I'm not having a problem with wait_closed() blocking indefinitely like I was before.
b) continued.. I'm using this [code](https://pastebin.com/GQ6KMK81) except that I uncommented the wait_closed line and added 'await' to the front so it looks like this: await server.wait_closed() Just now, it's clearing it just fine. I've been bouncing between 3 different computers while working with this. Perhaps my experience with this issue earlier was because of something in the environment of one of these machines. I sincerely apologize if that is the case...

Lastly, I've written up a [version](https://pastebin.com/N8t3HPpn) of this "color_server" using your suggestion to async with websockets.serve(). I implemented the multiple simultaneous servers with an extra function so it's a little bit more complicated. But it seems to function just as well as the code I posted to SO. Is there any reason you might suggest one approach over the other?

**Comment by aaugustin** [comment]
No worries.

If the pattern in the color_server script helps starting new servers quickly and keeping track of old servers until they finish closing all connections (including connections that may be stuck), that's cool.

I think we've gotten to the bottom of this question, so I'm going to close the issue.
