### ISSUE TITLE
Asyncio Fatal Error on SSL Transport - IndexError Deque Index Out Of Range

### ISSUE THREAD

**Issue by m-emori** [aaugustin/websockets#817]
When using SSL with websocket, _process_write_backlog function throws IndexError.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 1051, in read_frame
    extensions=self.extensions,
  File "/usr/local/lib/python3.7/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 473, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.7/asyncio/sslproto.py", line 689, in _process_write_backlog
    del self._write_backlog[0]
IndexError: deque index out of range
```

Websocket has a keepalive feature and periodically pings the server.
If ping sending process occurs at the same time when sending data, the data operation to the array (_write_backlog) will be duplicated, and the error will occur.

asyncio/sslproto.py
```
class SSLProtocol(protocols.Protocol)
    def _write_appdata(self, data):
        self._write_backlog.append((data, 0)) <--- append data to _write_backlog
        self._write_buffer_size += len(data)
        self._process_write_backlog()

    def _process_write_backlog(self):
        del self._write_backlog[0]  <--- !!!ERROR!!! IndexError: deque index out of range
```

When I asked a question on the python bug tracker, it was an issue in the websocket package.
It can be solved by excluding data transmission process as follows.
Can it be dealt with?

https://bugs.python.org/issue41596

site-packages/websockets/protocol.py
```
class WebSocketCommonProtocol(asyncio.Protocol):
    def __init__(
        self._write_sync = threading.Lock() <--- create lock object

    async def write_frame(
        self, fin: bool, opcode: int, data: bytes, *, _expected_state: int = State.OPEN
    ) -> None:

        with self._write_sync: <--- sync data send
            frame.write(
                self.transport.write, mask=self.is_client, extensions=self.extensions
            )
```

## Environments:
  * debian 4.19.46
  * Python 3.7.3
  * OpenSSL 1.1.0l  10 Sep 2019

**Comment by m-emori** [comment]
I used websocket in multiple threads.
I close the issue temporary.

**Comment by Anushaggm** [comment]
I had the same issue.I installed asyncio=3.4.3  in my virtualenv.It solved the Problem.

**Comment by Zatura** [comment]
#### If you are someone reading this because of this stack trace and is struggling with this problem, like I did, this may help you.  
I was using `asyncio.run()` to run several async methods on my asynchronous program, the problem is that `asyncio.run` **spawn a new thread every time you call it.**
Your code may even work for some minutes, but eventually concurrency problem will arise on your websocket SSL and you will receive a stacktrace similar to that.
To solve that, instead of `asyncio.run()` method, use `loop.create_task()` from the main asyncio event loop, then, instead of a new thread, it would spawn a new task at the same main thread.
Note that you SHOULD NOT use `run()`, `run_until_complete()`, `run_foverever()` more than 1 time if your intention is running everything on the same thread and use tasks for that, because some of those methods are intended to run on the beginning and creation of the main thread and setting up the event_loop, if you call `run_until_complete` a second time for example, you will get an exception saying that you already have an event loop created.

**Comment by aaugustin** [comment]
Thank you for sharing. It's more related to asyncio than websockets, but people usually hit websockets' bug track before asyncio's :-)
