### ISSUE TITLE
Websocket keeps closing

### ISSUE THREAD

**Issue by jsmith7342** [aaugustin/websockets#83]
Hi,
I am trying to make a web controlled joystick that streams data from a web browser to a Raspberry Pi. I am able to connect, send a message and receive a message back, however immediately after this it disconnects. I've read your API and it seems to mention this behaviour, however I cannot find how to disable it, to keep the connection alive. Could someone provide example Python + preferably HTML to keep a connection open?
![image](https://cloud.githubusercontent.com/assets/13293301/11605671/76478926-9b51-11e5-9b9a-aa9a29ab576d.png)
![image](https://cloud.githubusercontent.com/assets/13293301/11605674/8ee2f128-9b51-11e5-93fd-3df302761af5.png)
The full HTML code is here: http://codepen.io/matt-west/pen/tHlBb

Thanks

**Comment by aaugustin** [comment]
Look at the [server example in the intro](http://websockets.readthedocs.org/en/stable/intro.html#browser-based-example). Notice it has a `while True` loop.

**Comment by jsmith7342** [comment]
Face palm!

**Comment by aaugustin** [comment]
In your defense, this question keeps coming and I haven't written a FAQ yet... If you'd like to add one to the docs, we can work on that.

**Comment by nathanandersen** [comment]
I would like to do this too - but I don't want it to be blocking.
Effectively, I want a server that pushes updates to ALL clients every X seconds - I am accomplishing this by scheduling a repeated task (ai.sleep, await task) against the queue. So, the behavior I am looking for is as follows:
When a client connects on a certain path, I want to add them to a user set, and then keep that connection open, so I can push out the updates. Otherwise, I want to be able to remove them appropriately and close the connection.

**Comment by nathanandersen** [comment]
Here is a code excerpt from my project that is my current solution, modeled on top of the documentation for "Synchronization".
`
async def ping(self):
    return 1

async def handler(socket, path):
    if path == live_path:
        _repeat(ping, 1)      
   else:
       send_data_batch()

await websockets.serve(handler, host, port)
`
