### ISSUE TITLE
Release version 9.0

### ISSUE THREAD

**Issue by leszekhanusz** [aaugustin/websockets#845]
Sorry to be that guy.

The last release was exactly one year ago today. Is there a plan for a new release ?

Thank you.

**Comment by aaugustin** [comment]
Hello! Could you clarify which features/bugfixes are currently available in master, but not in the latest releases, and you're missing? Python 3.9 support maybe?

I'm asking because I usually make releases after major features/bugfixes. The only major feature that I remember since the last release is the Sans-I/O interface. it isn't documented (nor used internally) so it's still a private API at this point.

**Comment by leszekhanusz** [comment]
This is really nothing much, but yes indeed it is for python 3.9 for the gql package to solve a deprecation warning.
See issue [gql #161](https://github.com/graphql-python/gql/issues/161)

**Comment by aaugustin** [comment]
OK, thanks for the clarification. Python 3.9 was released less than a month ago, so it's not like the issue lingered for a year.

One of the rare positive side effects of the lockdown is that I tend to have more time for open-source than I would otherwise have. I'll see what I can do.

Making a release would be faster than typing this comment -- git tag 8.2 && git push --tags. However, it requires some availability in case something goes wrong. That's why I usually take time to review what happened since the last release. In this case, a large refactoring happened.

**Comment by aaugustin** [comment]
Good to see a non-crypto use of websockets, BTW :-) This gives me a bit of faith in the usefulness of this project!

**Comment by adriansev** [comment]
> Good to see a non-crypto use of websockets, BTW :-) This gives me a bit of faith in the usefulness of this project!

well, you can be assured that is really useful .. see https://github.com/adriansev/jalien_py (where ALICE means [this](https://alice-collaboration.web.cern.ch/) )

**Comment by aaugustin** [comment]
Whoa Adrian I had no idea that's how you used websockets, pretty cool!

**Comment by leszekhanusz** [comment]
>> Good to see a non-crypto use of websockets, BTW :-) This gives me a bit of faith in the usefulness of this project!

>well, you can be assured that is really useful .. see https://github.com/adriansev/jalien_py (where ALICE means this )

I can assure you that it is very useful for me as well, even if it is not LHC level :smile: (it will be used for remote maintenance of thousands of buses and trams communication systems)

And with 3k stars on GitHub, I am sure this library is certainly useful to a lot of other people!

I just ran our test suite against the websockets master branch and everything seems to work after I modified our code to import `HeadersLike` from `websockets.datastructures` instead of `websockets.http`.

There is just another new deprecation warning which appeared:

```python
/home/leszek/miniconda3/envs/gql-dev/lib/python3.8/site-packages/websockets/framing.py:27: DeprecationWarning: websockets.framing is deprecated
    warnings.warn("websockets.framing is deprecated", DeprecationWarning)
```

See the tests on my [testing_new_websockets branch](https://github.com/leszekhanusz/gql/tree/testing_new_websockets) if you are interested

**Comment by aaugustin** [comment]
Yes there was a bit of API churn in master due to the Sans-I/O refactor.

See https://github.com/aaugustin/websockets/blob/master/docs/changelog.rst#90

**Comment by aaugustin** [comment]
Fun fact: I started websockets because WebSocket looked like a reasonable protocol for talking with stationary batteries at a [company](https://www.blue-solutions.com/en/) that also did electric buses and trams. I left that job shortly thereafter and never used websockets for anything serious but I'm still maintaining it. Your usage of websockets to talk to buses and trams sort of goes full circle :-)

**Comment by aaugustin** [comment]
Looking at what you wrote, I should make types like `HeadersLike` public APIs.

**Comment by aaugustin** [comment]
So I'm starting to go through issues and figure out what I want to put in 9.0.

I may want to include a "sync" version (i.e. based on socket + threading) which is likely the easiest way to prove that the Sans-I/O version serves a purpose.

**Comment by aaugustin** [comment]
At this point the most likely ETA looks like "EOY 2020".

**Comment by johnthagen** [comment]
Any update on this in 2021?

**Comment by aaugustin** [comment]
The situation is a bit tricky due to the library being in the middle of a huge refactoring and $DAY_JOB leaving very little free time for open source work :-/

I was on holidays last week and did a bit of work on the documentation that was a prerequisite for a release.

**Comment by aaugustin** [comment]
https://pypi.org/project/websockets/9.0/
