### ISSUE TITLE
test_keepalive_ping_does_not_crash_when_connection_lost intermittent failure on openSUSE zSystems s390x

### ISSUE THREAD

**Issue by jayvdb** [aaugustin/websockets#855]
This is occurring against 8.1 release, and isnt occurring on other platforms.

```py
[   48s] ======================================================================
[   48s] ERROR: test_keepalive_ping_does_not_crash_when_connection_lost (tests.test_protocol.ServerTests)
[   48s] ----------------------------------------------------------------------
[   48s] Traceback (most recent call last):
[   48s]   File "/home/abuild/rpmbuild/BUILDROOT/python-websockets-8.1-28.1.s390x/usr/lib64/python3.8/site-packages/websockets/protocol.py", line 838, in transfer_data
[   48s]     await asyncio.shield(self._put_message_waiter)
[   48s] asyncio.exceptions.CancelledError
[   48s] 
[   48s] The above exception was the direct cause of the following exception:
[   48s] 
[   48s] Traceback (most recent call last):
[   48s]   File "/home/abuild/rpmbuild/BUILD/websockets-8.1/tests/test_protocol.py", line 1199, in test_keepalive_ping_does_not_crash_when_connection_lost
[   48s]     self.loop.run_until_complete(self.protocol.recv())
[   48s]   File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
[   48s]     return future.result()
[   48s]   File "/home/abuild/rpmbuild/BUILDROOT/python-websockets-8.1-28.1.s390x/usr/lib64/python3.8/site-packages/websockets/protocol.py", line 509, in recv
[   48s]     await self.ensure_open()
[   48s]   File "/home/abuild/rpmbuild/BUILDROOT/python-websockets-8.1-28.1.s390x/usr/lib64/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
[   48s]     raise self.connection_closed_exc()
[   48s] websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

**Comment by aaugustin** [comment]
Is it still flaky when env variable `WEBSOCKETS_TESTS_TIMEOUT_FACTOR` is set to `10` or `25`?

**Comment by jayvdb** [comment]
I set `WEBSOCKETS_TESTS_TIMEOUT_FACTOR=10` and have done a few rebuilds, and not seen any failures.
But to be honest it was quite infrequent that I saw this failures.

**Comment by aaugustin** [comment]
Then I suggest you keep WEBSOCKETS_TESTS_TIMEOUT_FACTOR big enough to avoid issues.

To give you a bit of background of this...

Some tests in websockets are based on timings. This is bad. I don't know how to rewrite all these tests without depending in timings — and there's better use of my time spent maintaing this library.

I'm using fairly short timings because I'm try to keep the test suite fast. It used to run in less than 1s. Now it drifted to 2,5s. This is bad too.

So I ended up keeping very short timings by default, which usually work in local development, and multiplying all timings by a large factor in CI, which often runs on overloaded shared cloud servers and where flakiness is more annoying (vs. redoing a test run that takes less than 3s).

WEBSOCKETS_TESTS_TIMEOUT_FACTOR is the (undocumented) way to achieve this.

**Comment by aaugustin** [comment]
(heavy sigh)

**Comment by jayvdb** [comment]
No worries.  Thanks for the explanation.
