### ISSUE TITLE
Intercepting Ping Frames

### ISSUE THREAD

**Issue by paulj-net** [aaugustin/websockets#884]
Is there a way to intercept the ping frames?  I currently have a websocket client setup up using this simplified structure:

```
loop = asyncio.get_event_loop()
            websocket = loop.run_until_complete((open_websocket(token)))

async def open_websocket(token):
        async with websockets.connect(ws_endpoint, ssl=ssl_context, ping_interval=None) as ws:
            await message_receiver(ws)

async def message_receiver(ws):
    async for message in ws:
        ....do something with message....
```

My message receiver doesn't trigger when receiving ping frames.  Is there a way to run a function when a ping frame is received, prior to sending the pong?

**Comment by aaugustin** [comment]
There's no public API for this — because I'm not aware of a use case. What's the use case?

If you really need this and you're willing to use a private API, you can subclass `WebSocketClientProtocol`, graft your logic in the subclass, and pass the subclass in the `create_protocol` argument of `connect`.

**Comment by paulj-net** [comment]
Here's the use case.  I have a service that I've written in python and wrapped up with systemd.  I want to set this service to restart if the systemd watchdog fails using https://github.com/bb4242/sdnotify and I thought a great place to tie that logic in would be the ping/pong commands already being sent as part of the keep_alive for the websocket.  If I'm not getting pings I could restart the service.

**Comment by aaugustin** [comment]
I suppose you're talking about a client rather than a server.

What about using built-in functionality instead?

- Configure `ping_interval` and `ping_timeout` if you don't like the defaults (20 seconds each)
- Have your service exit when there's a ping timeout — usually this "just happens" without any effort because `recv()` raises connection closed, but you can also handle explicitly with `await websocket.wait_closed()` and triggering an exit when this calls returns.

Then you'll get the behavior you want.

**Comment by paulj-net** [comment]
That's right it is a websocket client.  I was using the ```ping_interval``` originally but due to a buggy implementation in the websocket server I'm connecting to I discontinued and have set ```ping_interval=None```.  This way I'm only responding to the pings sent from the server instead of also sending my own pings.  When I sent my own the server would not respond forcing a restart of the websocket client.

I guess my primary issue is that occasionally my script stops functioning.  I haven't been able to fully diagnose the issue but my quick fix idea was to use systemd's watchdog to restart the script if my client stops receiving pings from the server I connect to.

**Comment by aaugustin** [comment]
How annoying. Then I don't have a better solution to offer than the gross hack.

**Comment by paulj-net** [comment]
Haha.  Thank you for your help.
