### ISSUE TITLE
 how to implement websockets with django?

### ISSUE THREAD

**Issue by 45duro** [aaugustin/websockets#890]

**Comment by aaugustin** [comment]
Marking as a documentation issue because it would be good to have this in the FAQ.

You have two options:

1. Don't use websockets. Use [Django Channels](https://channels.readthedocs.io/en/stable/). This allows you to use the same code base for handling regular HTTP requests and WS messages.

2. Use websockets. Set a `DJANGO_SETTINGS_MODULE` env var and run `django.setup()` before starting a process. Run blocking operations (like ORM calls that query the database) with [loop.run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor).

Either solution works well. There's no definitive reason to prefer one over the other.

**Comment by 45duro** [comment]
> Marking as a documentation issue because it would be good to have this in the FAQ.
> 
> You have two options:
> 
> 1. Don't use websockets. Use [Django Channels](https://channels.readthedocs.io/en/stable/). This allows you to use the same code base for handling regular HTTP requests and WS messages.
> 2. Use websockets. Set a `DJANGO_SETTINGS_MODULE` env var and run `django.setup()` before starting a server. Run blocking operations (like ORM calls that query the database) with [loop.run_in_executor](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor).
> 
> Either solution works well. There's no definitive reason to prefer one over the other.

I'm working with OCPP and Websockets, the problem happen when I try join these to Django. Channels and OCPP aren't compatible. Can you   explain me your advice number 2?,  thank you

**Comment by aaugustin** [comment]
Solution 2 consists in running a server written with websockets, where you import models (or other structures) built with Django. This server runs separately from your HTTP Django service — similar to how your task runner (celery, rq, etc.) runs separately from the HTTP Django service.

There are two requirements to make this work, on which I'm going to expand a bit.

When you run Django-related without going through its usual entrypoints (WSGI, ASGI, or management commands) you must do this: https://docs.djangoproject.com/en/stable/topics/settings/#calling-django-setup-is-required-for-standalone-django-usage

While some layers of Django can be used asynchronously, other layers cannot: their API consists of functions that make blocking network calls. The ORM is usually the major concern. `asyncio` provides a solution for this: https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor

**Comment by aaugustin** [comment]
I'm planning to write more, but this should already give you a good grasp of the solution I'm proposing.
