### ISSUE TITLE
compression causes indefinite memory growth

### ISSUE THREAD

**Issue by medariox** [aaugustin/websockets#896]
I was debugging a memory leak in my code and found out it was caused by `websockets\extensions\permessage_deflate.py`.

This is an excerpt of `tracemalloc`:
```
top_current: 1 site-packages\websockets\extensions\permessage_deflate.py:0: size=606 KiB, count=41, average=14.8 KiB
top_current: 1 site-packages\websockets\extensions\permessage_deflate.py:0: size=907 KiB, count=58, average=15.6 KiB
top_current: 1 site-packages\websockets\extensions\permessage_deflate.py:0: size=1209 KiB, count=75, average=16.1 KiB
top_current: 1 site-packages\websockets\extensions\permessage_deflate.py:0: size=1511 KiB, count=92, average=16.4 KiB
top_current: 1 site-packages\websockets\extensions\permessage_deflate.py:0: size=1812 KiB, count=109, average=16.6 KiB
top_current: 1 site-packages\websockets\extensions\permessage_deflate.py:0: size=2114 KiB, count=126, average=16.8 KiB
top_current: 1 site-packages\websockets\extensions\permessage_deflate.py:0: size=2416 KiB, count=142, average=17.0 KiB
top_current: 1 site-packages\websockets\extensions\permessage_deflate.py:0: size=2717 KiB, count=159, average=17.1 KiB
```

This was observed with the client and after calling close(). Obviously disabling the compression fixes the memory leak.
I'm reporting this as I don't think it is the expected behavior, feel free to close the issue if otherwise. Thank you.

`websockets version: 8.1`
`Python version: 3.7.7 64bit`
`OS: Windows 10 64bit`

**Comment by aaugustin** [comment]
Are you sure you no longer have any reference to the client object (= the object returned by `await connect()`) when you make this measurement? When the client is garbage collected, this memory should be released. If you still have a reference to the client, it isn't a memory leak.

To be clear, I suspect you still have a memory leak after you disable compression, just a smaller one (because compression context takes a lot more memory than the rest of the connection object) :-)

You could make an argument for setting a bunch of attributes to `None` when the connection is closed, in order to release memory slightly faster, but this will have minimal effect in most practical consequences.

**Comment by medariox** [comment]
Thank you for the quick reply!

You are completely right. I was expecting the `close()` to also clear the object internals. 
Since this is by design, I will try to have it fixed in the upstream library that uses websockets.

**Comment by aaugustin** [comment]
Thanks for reporting back!

To be honest, this isn't really _by design_. Rather, it's the natural result of a straightforward implementation in Python.

I'd rather not make additional guarantees, because I'm not sure how I can enforce them over time; for starters it isn't obvious how to write a test. Rather, I expect users of the library to dispose of the connection object quickly after closing the connection.
