### ISSUE TITLE
Some questions about recv()

### ISSUE THREAD

**Issue by rcv911** [aaugustin/websockets#911]
Hi.

Let's say I've got a single socket connection.  I make _task_msg_ and do:
```python
await ws.send(task_msg)
```
then I need check answer. So, I can check constantly like this

```python
tries = 60
for i in range(tries):
    response = await ws.recv()
    # //some logic and handles which break loop
    asyncio.sleep(1)
```
or I can use pattern:

```python
async def consumer_handler(ws, path):
    async for msg in ws:
        await consumer(msg)
```
but iteration terminates when the client disconnects.

1) What if I don't need client disconnecting and I need possibility handle coroutines? If it possible
2) What is the exit condition from consumer_handler except client disconnection? If it exists

Supposing I need handle 3 coroutines in one connection
```python
coros = [run_task(task) for task in tasks]
done, pending = await asyncio.wait(coros)
```

and I got smth like this:
```
done = {
	<Task finished coro=<...> result=True>,
	<Task finished coro=<...> exception=RuntimeError('cannot call recv while another coroutine is already waiting for the next message')>,
	<Task finished coro=<...> exception=RuntimeError('cannot call recv while another coroutine is already waiting for the next message')>
}
```

**Comment by aaugustin** [comment]
You don't need that kind of loop.

```python
response = await ws.recv()
```

will return only when you get an answer.

Re 1. you can't call `recv()` in multiple coroutines in parallel because this would result in non-deterministic behavior: which coroutine would get which message?

Re 2. the other exit condition is simply if you exit the handler coroutine. Then websockets takes care of closing the connection.
