### ISSUE TITLE
Stop client on signal

### ISSUE THREAD

**Issue by tobias-schuele** [aaugustin/websockets#933]
How do I stop a client, which continuously processes messages, when a signal is received (similar to https://websockets.readthedocs.io/en/stable/deployment.html?highlight=signal#graceful-shutdown)?

**Comment by aaugustin** [comment]
There are two solutions:

1. you can write an infinite loop where you await both the next message with `client.recv()` and the `stop` future used for exiting, returning when the first one completes;
2. you can write a signal handler that starts a task that runs `client.close()` (you need to start a task because you cannot run a coroutine in a signal handler, I believe)
