### ISSUE TITLE
Release 9.0 breaks mypy

### ISSUE THREAD

**Issue by vertti** [aaugustin/websockets#940]
Running a project that uses websockets 9.0 against mypy, throws:

```
error: Module has no attribute "connect"
```
for 
```python
import websockets
await websockects.connect(uri)
```

and
```
Module 'websockets' has no attribute 'connect'
```
for 
```python
from websockets import connect
```

Version 8.1 of websockets has no such issue. Using the latest mypy 0.812.

**Comment by apljungquist** [comment]
I expect this is caused by the new lazy import system. Another consequence of this is that trying to jump to definitions no longer works (one always lands in the package dunder init file) which is unfortunate since the ability to quickly inspect third party code is one of my favourite features of python.

**Comment by aaugustin** [comment]
Oh, the joy.

**Comment by gmjosack** [comment]
The lazy importer also breaks pylance, similar to the error for mypy, as well as pyinstaller as it fails to include the correct modules in the distribution. 

as a work around I'm currently using 

```py
from websockets.legacy.client import connect as ws_connect
```

which resolved both issues.

**Comment by aaugustin** [comment]
This is the pragmatic workaround at this point. I hate that it exposes the `.legacy` package before the new package is ready, but I'm not coming up with something better.

https://stackoverflow.com/questions/60739889/bypass-mypys-module-has-no-attribute-on-dynamic-attribute-setting has a good discussion of the options and they're all bad :-(

**Comment by aaugustin** [comment]
Could you report whether https://github.com/aaugustin/websockets/commit/a7b240064b579f0c1a5b14d5404646bf289092f3 works?

Supported uses should include:

```python
import websockets.client
await websockects.client.connect(uri)
```

and

```python
from websockets.client import connect
await connect(uri)
```

(This will have to be a bugfix release on top on 9.0.1, but I never did maintenance branches in websockets, so this isn't a request.)

**Comment by ltworf** [comment]
You could have at least put a changelog file to say that the api was changing.

Also semver would be nice.

**Comment by ltworf** [comment]
In any case, changing the import seems to work but doesn't satisfy mypy.

`slackclient/client.py:63: error: Name 'websockets.client.WebSocketClientProtocol' is not defined`

**Comment by ltworf** [comment]
Well imports are code.

Specifically now I have the problem that distributions use one version, pip installs another and I don't know if I can make code compatible with both.

Also mypy fails even after fixing the imports so that doesn't help so much.

**Comment by aaugustin** [comment]
@ltworf -

> You could have at least put a changelog file to say that the api was changing.

I did. That didn't help since you didn't read the changelog before complaining.

> Also semver would be nice.

websockets follows semver. While [semver doesn't work](https://hynek.me/articles/semver-will-not-save-you/), some folks like it and and would complain otherwise; making them happy doesn't cost much.

> either it's not semver or it breaks API all the time

Well that's just one of the reasons why semver doesn't work. Due to [Hyrum's law](https://www.hyrumslaw.com/), given enough users, many kinds of changes could be breaking change for some users, so the major version number changes often. I suspect some of these "possibly breaking" changes didn't actually affect anyone.

Please consider the effect that the patronizing tone of your comments has on my willingness to work for you for free.

The immediate effect is that my motivation to work on this bug, which doesn't affect me personally, dropped a lot 🤷 

@gmjosack -

Thanks for pointing out that, even with the best intentions, mistakes can happen.

**Comment by ltworf** [comment]
> I did. That didn't help since you didn't read the changelog before complaining.

I downloaded the .tar.gz and there is no changelog file, so unless you mean I clone the repo and check all the commits, there is no changelog.

> Please consider the effect that the patronizing tone of your comments has on my willingness to work for you for free.

I use your library in a open source project that I maintain in my free time and for which I have never received a single donation.

So now because of your breaking changes I'm on a sunday debugging things because those changes completely break my project for my (non paying) users.

**Comment by scottbelden** [comment]
@ltworf If this is really such a big issue for you then you should pin all of your dependencies. I too was affected by this and the solution was quite simple. Quickly make a commit to pin the dependency to `<9.0` and then come back to it with a better fix once there is one.

I too maintain an open source project and it baffles me that you do as well but then choose to come harass the maintainer here. Since any change in a dependency could break end users, you should probably pin all of your dependencies or maintain forks of all of your dependencies so that you can properly vet all changes.

**Comment by apljungquist** [comment]
> Option 1bis - hide .legacy ... I think this is my favorite option.

I agree that this is a good option and it appears to work for a [simple example](https://gist.github.com/apljungquist/3bb1f616f74fff3e7003fbd14600cf75). However, if IDEs and other development tools prefer this pattern, then it could become widespread making the deprecation warnings less useful.

Btw, I noticed that websockets dunder init does not use `lazy_import` as is suggested by its docstring. Indeed it seems that [doing so](https://github.com/apljungquist/websockets/commit/5456f0f2060c0bfcda8a5280eef91eb782f324dc) resolves the problem.

**Comment by ltworf** [comment]
@scottbelden 

pinning dependencies and embedding stuff is a sure way of making sure your project will never be included in a distribution. I have done that but I also need to make a minor release so that potential users downloading the latest release get something that works.

But long term this is no solution.


> I too maintain an open source project and it baffles me that you do as well but then choose to come harass the maintainer here. 

Stating that there is no changelog and that changing the import doesn't make mypy happy is facts, not harassment. It is providing relevant facts for the resolution of the issue.

And again pinning dependencies is not a good thing and when developing a library it is good to keep compatibility in mind, when possible.

I'm not saying all projects should be like the linux kernel and keep bugs for the sake of remaining compatible forever, but there is a middle ground between that and the opposite extreme of renaming all the functions every release.

**Comment by aaugustin** [comment]
The conversation diverged quite a bit from the original issue so I'm going to lock it and go back to solving the issue.

**Comment by aaugustin** [comment]
@apljungquist -

Thanks for testing and providing feedback!

Also, yes, I briefly considered the `if TYPE_CHECKING:` plan and ended up with the same conclusion as you:

- at this point, better scratch the dynamic import system as its benefits are lost (ease of moving things around to refactor);
- also, websockets jumps through hoops in a couple places (e.g. imports at the bottom of files) to avoid `if TYPE_CHECKING` and I'd rather not introduce it.

**Comment by aaugustin** [comment]
I just released 9.0.2 with the fix.

**Comment by apljungquist** [comment]
Thanks a bunch.

**Comment by aaugustin** [comment]
Apologies for the disruption!

**Comment by aaugustin** [comment]
For whoever ends up here: try this:

```python
from websockets.client import connect
from websockets.server import serve
```

if mypy or other tools that don't understand the dynamic nature of Python give you false positives.

**Comment by ThatXliner** [comment]
For those using pylint, I wrote a(n experimental) [pylint plugin for this](https://pypi.org/project/pylint-websockets/)

**Comment by DevilXD** [comment]
@aaugustin I'm on v10.1 and this doesn't work with MyPy nor Pylance: https://i.imgur.com/y1UDAPl.png

The only modules that work are `lazy_import` and `version`, everything else is hidden behind `__init__.py` and its lazy import system.

Using `if TYPE_CHECKING` imports is perfectly fine for typed code, not sure why are you trying so hard to avoid it. It has to be used at the top of the file, to import things for type checking purposes only, that'd otherwise create import cycles. Similarly, if your "lazy import" system is there only to avoid having to deal with import cycles, it's perfectly fine to import things within functions, like so: https://github.com/DevilXD/aRez/blob/master/arez/match.py#L469

Imports are persistent, meaning that once you import something once, any subsequent import is going to just link the already imported module from memory instead of executing it again. Alternatively, you can avoid import cycles by using just `import XYZ` instead of `from XYZ import ABC` form. Both solutions end up having negligible performance impact, equal to a single extra attribute lookup.

`TYPE_CHECKING` import example: https://github.com/DevilXD/aRez/blob/master/arez/match.py#L14

I'm extensively using typed code and MyPy for early error detection and type hinting purposes, and the way it is right now, makes it literally impossible, short of modifying `sys.path` to bypass your `__init__.py` and importing your classes directly from the package folder.

**Comment by aaugustin** [comment]
@DevilXD There's a typo in that screenshot. Try `from websockets.client import ...` instead of `from websocket.client import ...`.

**Comment by aaugustin** [comment]
For the record, the lazy import mechanism is intended to avoid loading the server code when you're only going to use the client code and vice-versa. I am ready to admit that it's a nano-optimization no one cares about. The CPU and memory impact of loading an unused module isn't very high. That said, unless you're a Tidelift subscriber, you paid $0 for this software. For that price, you can probably bear with my quirks 🤷 

I appreciate that you wanted to give me some context about how imports work in Python. I happen to [have a bit of domain expertise](https://www.youtube.com/watch?v=o7edMNyZCZw) in this area, especially import cycles.

Lazy imports don't really help with import cycles. If anything, they make the situation more confusing, as they make the import sequence less deterministic.

**Comment by ltworf** [comment]
> Please consider the effect that the patronizing tone of your comments has on my willingness to work for you for free.

> That said, unless you're a Tidelift subscriber, you paid $0 for this software. For that price, you can probably bear with my quirks shrug

To be fair, you are quite free to release this as proprietary software.

What I do is that I use GPL license, and I'm open to give LGPL exceptions for money (which has never once happened).

In this way I know that people who don't pay are doing libre software, so they are welcome to use my stuff for free.

Those who want to make proprietary stuff (and are most likely making money from it) generally end up not using my project.

**Comment by aaugustin** [comment]
In fact I'm happy if people use websockets and make money with it (preferably in an environmentally responsible way). I'm not really trying to monetize it.

When I bring up the price, it's usually a signal that the discussion crossed a frontier and I don't think the feedback is going to help me improve websockets.

**Comment by DevilXD** [comment]
> @DevilXD There's a typo in that screenshot. Try `from websockets.client import ...` instead of `from websocket.client import ...`.

Hmm, that appears to have worked. I'm not sure how I've missed that yesterday, I guess it's my mistake then.

> For the record, the lazy import mechanism is intended to avoid loading the server code when you're only going to use the client code and vice-versa. I am ready to admit that it's a nano-optimization no one cares about. The CPU and memory impact of loading an unused module isn't very high. That said, unless you're a Tidelift subscriber, you paid $0 for this software. For that price, you can probably bear with my quirks :shrug:

I see. I'm sorry if this came out harsh to you, but out of frustration, I seriously considered looking for a different package yesterday, one that would allow we to type check my code properly. If you really are happy that others use websockets, then it only makes sense to not make it unnecessarily difficult to use them. Am I right?

**Comment by aaugustin** [comment]
Yes, it makes sense :-) I'm glad you're sticking with websockets :-)

**Comment by aaugustin** [comment]
439dafa6 should solve the problem fully going forwards.
