### ISSUE TITLE
Importing self by absolute name breaks including a modified version directly into a project

### ISSUE THREAD

**Issue by EternityForest** [aaugustin/websockets#946]
Through no fault of websockets, I have to use a patched version to get around an android DNS resolution bug.

However, importing "websockets" from within the module tries to get the system package instead.  This seems like it could
potentially cause confusion for devs at some point, as it seems to mix the ocal folder and installed package in an hard to think about way. Would relative imports be better?

It seems to only need two changes, in legacy framing:

 # at the bottom to allow circular import, because Extension depends on Frame
-import websockets.extensions.base  # isort:skip # noqa
+from ..extensions import base  # isort:skip # noqa

And in frames.py:
 
 # at the bottom to allow circular import, because Extension depends on Frame
-import websockets.extensions.base  # isort:skip # noqa
+from .extensions import base  # isort:skip # noqa

**Comment by aaugustin** [comment]
Do you mean you're copy pasting websockets inside a module of your own, so it becomes `my_project.websockets`?
It turns out that most imports are relative inside websockets, so this almost works, but this isn't a supported use.
If you change websockets' import path then you have to adjust imports, that's expected (duh).

I'll try to make the change you're requesting because it seems simple and harmless, but there's zero guarantee of backwards-compatibility. If I need to go back for any reason I'll do it.

Also I would strongly encourage you to understand relative vs. absolute imports + PYTHONPATH rather than hack around without understanding the rules.

One possible cause:

- when you're in a sibling module inside your project, `import websockets` works as a relative import (not sure these still work in Python 3; they did in Python 2 but should be avoided precisely because they trigger the problem you have)
- when you're elsewhere, `import websockets` gives you the system version.
