### ISSUE TITLE
No module named websockets.legacy on compiled

### ISSUE THREAD

**Issue by Jonirulah** [aaugustin/websockets#974]
I have a problem that only presents itself after compiling to a binary file. I tried compiling the script in Python 3.7-3.8-3.9 with Nuitka and PyInstaller and it's been happening every time.

The thing here is that is perfectly fine in the .py script but when compiling I have the issue, I did check that websockets legacy folder is located where it should be, reinstalling the lib, trying another python version, with different compilers, does someone know anything about it?

Thanks!

<img src="https://media.discordapp.net/attachments/491048464831086592/847258410969595914/707a46792063f73dff9e02d081a56a1c.png">

**Comment by aaugustin** [comment]
If the app works fine with CPython and fails with Nuitka, that's a Nuitka bug, isn't it?

Not the first time we have very bizarre issues involving Nuitka, see #699 :-/

**Comment by PieceOfGood** [comment]
Hello!
I wrote my wrapper over the Chrome Devtools protocol and the only dependency in it is this library. On versions older than 8.1, when compiling with the help of the pinstaller, this error always appears. If you just run it as a *.py script, everything works as expected.
I expected this to be fixed in future releases, but it doesn't. Probably because very few people distribute their Python work as executable files for Windows. Unfortunately, because of this, for the second year now I have to use version 8.1.

```
Traceback (most recent call last):

  File "main.py", line 3331, in <module>

  File "asyncio\runners.py", line 44, in run

  File "asyncio\base_events.py", line 603, in run_until_complete

  File "asyncio\windows_events.py", line 316, in run_forever

  File "asyncio\base_events.py", line 570, in run_forever

  File "asyncio\base_events.py", line 1859, in _run_once

> File "asyncio\events.py", line 81, in _run

  File "main.py", line 3224, in main

  File "main.py", line 1864, in _run_ui

  File "asyncio\tasks.py", line 494, in wait_for

  File "aio_dt_protocol\BrowserEx.py", line 51, in GetPage

  File "aio_dt_protocol\BrowserEx.py", line 42, in GetPageBy

  File "aio_dt_protocol\Page.py", line 265, in Activate

  File "websockets\imports.py", line 81, in __getattr__

  File "websockets\imports.py", line 26, in import_name

ModuleNotFoundError: No module named 'websockets.legacy'
```

**Comment by aaugustin** [comment]
> I expected this to be fixed in future releases

Your script works well when you run in standalone; it doesn't work once packaged; so I think this is a problem with the way you package it. How do you package?

I'm unable to help because I don't have access to a Windows environment and I cannot reproduce the problem.

---

I suppose `aio_dt_protocol\Page.py` does something like `import websockets` and then on line 265 `await websockets.connect`, can you confirm? (Pretty hard to reverse engineer this because the stack trace you provided doesn't include the code, unlike regular Python stack traces.)

If so, try `import websockets.client` and `await websockets.client.connect`. Perhaps that won't trigger the bug in the packaging system.

**Comment by PieceOfGood** [comment]
Everything is exactly as you suggested. I did an import following your example and it worked!
It's all the fault of my laziness to read updates. Thanks for your work. She's great!

**Comment by aaugustin** [comment]
Good to hear it's resolved!

**Comment by amitgithub1** [comment]
> > I expected this to be fixed in future releases
> 
> Your script works well when you run in standalone; it doesn't work once packaged; so I think this is a problem with the way you package it. How do you package?
> 
> I'm unable to help because I don't have access to a Windows environment and I cannot reproduce the problem.
> 
> I suppose `aio_dt_protocol\Page.py` does something like `import websockets` and then on line 265 `await websockets.connect`, can you confirm? (Pretty hard to reverse engineer this because the stack trace you provided doesn't include the code, unlike regular Python stack traces.)
> 
> If so, try `import websockets.client` and `await websockets.client.connect`. Perhaps that won't trigger the bug in the packaging system.

This exactly solved my issue as well with nuikta. Thank you again.
